### ISSUE TITLE
[aws-vpc-cni] v1.14.0 added configmap with static name

### ISSUE THREAD

**Issue by sarahhodne** [aws/eks-charts#1003]
**Describe the bug**
As of chart version v1.14.0 (commit 98be2d7dd4c530d88ef4d6ab46c55c1319151a6b), there is now always a ConfigMap named `amazon-vpc-cni` installed, which does not depend on the release fullname in any way, which breaks a behaviour we used to rely on where we would install multiple releases of the VPC CNI in the same cluster.

Specifically, we do this as a way to do a staged rollout of the VPC CNI when there's a new version, as we've been hit with breakages in the past during a rollout. We set node selectors and node affinities on the different releases to avoid having multiple copies of the DaemonSet on the same node, but this allows us to e.g. have an `aws-node` release and an `aws-node-canary` release, where the latter only runs on nodes tagged as canary nodes, and the former runs on remaining nodes.

**Steps to reproduce**

1. Have two (or more) separate releases of the amazon-vpc-cni chart, prior to v1.14.0, with separate nodeSelector values to ensure they run on different nodes.
2. Upgrade one of them to v1.14.0. This succeeds without issue
3. Upgrade the second release to v1.14.0. This errors with:

```
rendered manifests contain a resource that already exists. Unable to continue with update: ConfigMap "amazon-vpc-cni" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "aws-node": current value is "aws-node-canary"
```

**Expected outcome**
The second upgrade succeeds and there is no conflict with existing resources (possibly by setting some values to adjust/disable the creation of this ConfigMap).

**Environment**

* Chart name: aws-vpc-cni
* Chart version: v1.14.0 (and v1.14.1)
* Kubernetes version: 1.25
* Using EKS: Yes, 1.25

**Additional Context**:

I tried to look for where this ConfigMap was used, but I was unable to find any uses of it? The chart doesn't seem to reference it, and the pods don't seem to have access to read ConfigMaps so it doesn't seem to be used at runtime.

**Comment by jdn5126** [comment]
Discussed at https://github.com/aws/amazon-vpc-cni-k8s/issues/2612
