### ISSUE TITLE
AWS for FluentBit helm chart

### ISSUE THREAD

**Issue by mforutan** [aws/eks-charts#101]
It would be very helpful to have a helm chart for [aws-for-fluent-bit](https://github.com/aws/aws-for-fluent-bit) in this repo,

There is a closed PR on [helm incubator repo](https://github.com/helm/charts/pull/15830) but didn't get enough attention as they don't accept any new chart.

**Comment by max-rocket-internet** [comment]
Then open a PR 🙂
