### ISSUE TITLE
Add loadBalancerClass to aws-load-balancer-controller chart

### ISSUE THREAD

**Issue by bdhobare** [aws/eks-charts#1031]
**Is your feature request related to a problem?**
Yes. Unable to configure `--load-balancer-class` through helm chart for `Service`s

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-load-balancer-controller

**Describe the solution you'd like**
Add support for `loadBalancerClass` in the chart.

**Describe alternatives you've considered**
Manually cloning the deployment files and setting `--load-balancer-class`  in the controller arguments.

**Comment by bryantbiggs** [comment]
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located
