### ISSUE TITLE
AWS LoadBalancer Controller mTLS spport

### ISSUE THREAD

**Issue by dimakievukraine** [aws/eks-charts#1053]
**Is your feature request related to a problem?**
WE want to establish mutual TLS connection with partners to secure data flow

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller

**Describe the solution you'd like**
Recently AWS introduced [Mutual authentication for Application Load Balancer](https://aws.amazon.com/blogs/aws/mutual-authentication-for-application-load-balancer-to-reliably-verify-certificate-based-client-identities/). Could you please add this feature to Helm chart?

**Describe alternatives you've considered**
No alternatives. Didn't research, but maybe use Envoy sidecar to handle mTLS.

**Comment by bryantbiggs** [comment]
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located
