### ISSUE TITLE
[aws-load-balancer-controller]: webhookNamespaceSelectors inconsistently applied

### ISSUE THREAD

**Issue by fullykubed** [aws/eks-charts#1085]
**Describe the bug**
In the `aws-load-balancer-controller` helm chart, the `webhookNamespaceSelectors` is not applied to all webhooks, only the first one.

**Steps to reproduce**

Deploy the helm chart with `webhookNamespaceSelectors` set.

**Expected outcome**

All webhooks in [this helm template](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/webhook.yam) should contain the the same `namespaceSelector` that is used [here](https://github.com/aws/eks-charts/blob/4c9d554fd7e0718ea8dea11c14c5249c51ee78c9/stable/aws-load-balancer-controller/templates/webhook.yaml#L26).

**Environment**

* Chart name: `aws-load-balancer-controller`
* Chart version: `1.7.2`
* Kubernetes version: `1.29`
* Using EKS (yes/no), if so version?: `v1.29.1-eks-b9c9ed7`

**Additional Context**:

We would like to apply this to limit the blast radius should the controller go down. Currently, if the webhook service is unavailable, all services in all namespaces cannot be updated even when they will never be of type `LoadBalancer`.

**Comment by jasminen** [comment]
Super important ☝🏼
I had to manually change that in the mutating webhook itself.
