### ISSUE TITLE
Add affinity and tolerations to the CNI Metrics Helper deployment template

### ISSUE THREAD

**Issue by oplat-softserve** [aws/eks-charts#1113]
**Is your feature request related to a problem?**
I cannot deploy a chi-metrics-helper to a specific node group by defining a tolerations and affinity parameters

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
cni-metrics-helper

**Describe the solution you'd like**
add 'affinity' and 'tolerations' parameters to the deployment template file

**Describe alternatives you've considered**
N/A

**Comment by bryantbiggs** [comment]
closing due to https://github.com/aws/eks-charts/pull/1119#issuecomment-2158087617
