### ISSUE TITLE
aws eks appmesh contraoller installation is failing 

### ISSUE THREAD

**Issue by 1vinodsingh1** [aws/eks-charts#1140]
**Describe the bug**
The installation is failing :

 
kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
error: failed to run '/usr/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/appmesh-controller master': remote: Not Found
fatal: repository 'https://github.com/aws/eks-charts/stable/appmesh-controller/' not found

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-db838b0", GitCommit:"366357151e0ea73b880aff8f78634fdf38d8eaab", GitTreeState:"clean", BuildDate:"2024-06-27T19:10:53Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1

**Comment by bryantbiggs** [comment]
change this: 
```diff
- kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
+ kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller/crds?ref=master"
```

you have one too many `/` after `crds`
