### ISSUE TITLE
Missing parameter for use of STS Regional endpoints

### ISSUE THREAD

**Issue by rafaelpereyra** [aws/eks-charts#125]
Hello, 

Using VPC endpoints creates DNS records for the services that include regional names. In order to use the STS regional endpoint it's required to pass en environment variable to the Go SDK (AWS_STS_REGIONAL_ENDPOINTS).

Helm chart should include this option as an override for the default variable value.

**Comment by fawadkhaliq** [comment]
This was fixed here: https://github.com/aws/eks-charts/pull/236
