### ISSUE TITLE
Latest aws-node-termination-handler install broken

### ISSUE THREAD

**Issue by jmymy** [aws/eks-charts#127]
Latest release bumped the tag for Spot instance handler. However, the image hasn't been uploaded to dockerhub so it fails to install with appVersion 1.4.0

https://github.com/aws/eks-charts/blob/v0.0.19/stable/aws-node-termination-handler/values.yaml#L6

edit the image isn't on dockerhub because it hasn't been released yet:
https://github.com/aws/aws-node-termination-handler/releases is still at 1.3.1

**Comment by bwagner5** [comment]
sorry for that delay! v1.4.0 aws-node-termination-handler has been released!   

https://github.com/aws/aws-node-termination-handler/releases/tag/v1.4.0
https://hub.docker.com/repository/docker/amazon/aws-node-termination-handler/tags?page=1

**Comment by jmymy** [comment]
Thanks!
