### ISSUE TITLE
Metrics Helper for AWS VPC CNI

### ISSUE THREAD

**Issue by TechDawg270** [aws/eks-charts#155]
The CNI Metrics helper resources [found here](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/config/v1.6) need to be reflected in the [aws-vpc-cni chart](../tree/master/stable/aws-vpc-cni). If given the green light I can gladly add this over the next few days

**Comment by jaypipes** [comment]
@TechDawg270 you are officially green-lit :) Go for it!

**Comment by mscam** [comment]
hello, is there any update on this?

**Comment by jdn5126** [comment]
Publishing the `metrics-helper` chart from https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/cni-metrics-helper to eks-charts repo is in our backlog, but no timeline currently

**Comment by jdn5126** [comment]
This is now done!
