### ISSUE TITLE
Kube proxy helm chart

### ISSUE THREAD

**Issue by mohsen0** [aws/eks-charts#156]
Currently, On the creation of an EKS cluster, Workload like AWS CNI, Kube proxy are created automatically (I wish they were not so we can manage them in helm).

Would you be against adding a chart for Kube proxy here?
Usecase here is we want to be able to enable metric endpoints without manual intervention.

https://github.com/aws/containers-roadmap/issues/657

**Comment by max-rocket-internet** [comment]
> I wish they were not so we can manage them in helm

FYI https://github.com/helm/helm/issues/6561

**Comment by clayvan** [comment]
FYI I asked this a few days before you with a little more traction: https://github.com/aws/eks-charts/issues/154

**Comment by pierluigilenoci** [comment]
@clayvan but very little more traction... 🤣

**Comment by chaipot** [comment]
[This](https://github.com/flexkube/kube-proxy-helm-chart) should help in meantime

**Comment by andrew-pickin-epi** [comment]
> [This](https://github.com/flexkube/kube-proxy-helm-chart) should help in meantime

@chaipot how does this help?

**Comment by jdn5126** [comment]
Closing this issue on this repo as it is a feature request. Please create an issue at https://github.com/aws/containers-roadmap/issues so it can be tracked by EKS project managers.

cc: https://github.com/aws/containers-roadmap/issues/2132 as a related issue. No chart would be needed if kube-proxy was absorbed/replaced :)
