### ISSUE TITLE
aws-vpc-cni: Bump Helm Chart to use version 1.6.3 (Was 1.6.2)

### ISSUE THREAD

**Issue by TBBle** [aws/eks-charts#171]
[AWS Docs](https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html) and [eksctl](https://github.com/weaveworks/eksctl/releases/tag/0.21.0) are now deploying 1.6.3. (Edit: Was 1.6.2 when the issue was submitted, see https://github.com/aws/eks-charts/issues/171#issuecomment-657477383)

That should be stable-enough to also apply to the Helm chart? (Unless this is frozen pending https://github.com/aws/amazon-vpc-cni-k8s/issues/758, I guess)

**Comment by stevehipwell** [comment]
It looks like [v1.6.3](https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/update-cluster.md) should be the current stable version in the Helm chart to match what's installed on the cluster by default?

**Comment by max-rocket-internet** [comment]
Done in https://github.com/aws/eks-charts/pull/205
Next version in https://github.com/aws/eks-charts/pull/206

**Comment by stevehipwell** [comment]
Thanks @max-rocket-internet, I found the PRs and got diverted before I could come back here to add a new comment. Do we know when these changes will be released?

From a lifecycle point of view it'd be great if commits to master were released immediately (like the GH Actions helm releaser), and tracked the versions in use by new EKS clusters.

**Comment by TBBle** [comment]
Indeed, looks like since I posted this issue, 1.6.3 become the recommendation via https://github.com/awsdocs/amazon-eks-user-guide/commit/9fbba2a71d39d75400e5bed61f175fc4e8d828f9

**Comment by jayanthvn** [comment]
The helm charts CNI version is already updated to v1.7.5 (current EKS default). Hence closing this issue.
