### ISSUE TITLE
App Mesh controller 1.0 upgrade misses new undocumented namespace label/selector

### ISSUE THREAD

**Issue by fincd-aws** [aws/eks-charts#194]
Both the readme and the pre_upgrade_check.sh miss checking the namespaces for the `mesh: <mesh-name>` label. This label was not present in installation of controller version 0.5 and no migration details for 1.0 controller, which only has examples with the new namespaceSelector.

The label is documented in `namespace.yaml` in the [App Mesh service docs](https://docs.aws.amazon.com/app-mesh/latest/userguide/mesh-k8s-integration.html#configure-app-mesh )
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-apps
  labels:
    mesh: my-mesh
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
```

Additionally, the [controller troubleshooting doc](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/2a3eadcb68b3ef8bd9ba1f618f6a81982045b6a3/docs/guide/troubleshooting.md) says there are two namespace labels but terminology is odd. 
The "appmesh.k8s.aws/sidecarInjectorWebhook" states is "required" for the injector, while unspecified "customized labels" are optional for a single-mesh setup. However, the "single Mesh selects all namespaces" method is not mentioned to be optional anywhere else.

The mechanic is introduced in the service docs through commit "Periodic update - 06/18/20-02:05pm PDT" 5788b680694b42eb920136224a5983831efa92b7 by adding the label to the namespace (above and in the [same commit](https://github.com/awsdocs/aws-app-mesh-user-guide/commit/5788b680694b42eb920136224a5983831efa92b7#diff-ec3c013f92d56a71f68487b8fe02d8f9R136) and namespaceSelector to the [Mesh CRD example](https://github.com/awsdocs/aws-app-mesh-user-guide/commit/5788b680694b42eb920136224a5983831efa92b7#diff-ec3c013f92d56a71f68487b8fe02d8f9R156-R158)
```yaml
        namespaceSelector:
          matchLabels:
            mesh: my-mesh
```

Usage of the namespaceSelector seems only mentioned in the new APIDesign and [APISpec](https://github.com/aws/aws-app-mesh-controller-for-k8s/blame/2a3eadcb68b3ef8bd9ba1f618f6a81982045b6a3/docs/reference/api_spec.md#L91-L104) and the redesign proposal `api_overview.png` in the legacy-controller branch docs/ folder.

One point of behavior is not mentioned that I can find: Removing the namespaceSelector matches no namespaces, but does that render this Mesh unusable, with no VirtualNode etc recognized in any namespace? Does the injector webhook not function for this mesh in any namespace?

The usage of namespaceSelector needs to be documented better both here in the installation guide (since [this](https://aws.github.io/aws-app-mesh-controller-for-k8s/guide/installation/ points to the helm chart readme), in the upgrade, and if reasonable, into the `pre_upgrade_check.sh`
For the script, a kubectl match against the AND "union" of both labels will point out if there are any namespaces labelled properly for both injector and the new label:
`kubectl get namespaces --selector mesh,appmesh.k8s.aws/sidecarInjectorWebhook`

**Comment by fawadkhaliq** [comment]
hi @fincd-aws, thanks for reporting the issue. We will improve the upgrade steps here to capture how selectors need to be handled

**Comment by cdenneen** [comment]
Is there any update on this? I'm actually stuck right now with the 1.0.0 upgrade causing some issues and would like to get everything upgraded to the latest stable charts but running into these issues.

**Comment by achevuru** [comment]
@cdenneen Can you elaborate on the issues you are running in to during the upgrade? Issue being discussed here is mainly a documentation issue and to improve the pre upgrade script. Are you looking for some examples on how the namespace selector should be specified in the Mesh spec? You can refer to any of the example walkthroughs (howto-k8s-*) @ https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs

**Comment by fawadkhaliq** [comment]
Added a note about mesh namespace selector in the upgrade instruction: https://github.com/aws/eks-charts/pull/279 - also linked the API doc and examples. If the API doc/examples are missing something, please don't hesitate to open an issue and we'll be happy to assist
