### ISSUE TITLE
aws-node-termination-handler: Helm chart gets scheduled on fargate instance 

### ISSUE THREAD

**Issue by limed** [aws/eks-charts#198]
The `aws-node-termination-handler` gets schedule on a fargate node whenever a fargate node gets deployed, but due to fargates limitation this chart will never get deployed because its a daemonset

Adding `affinity` to the manifest should fix this issue

**Comment by limed** [comment]
@bwagner5 any idea when the chart would be synced over to this repo? Thanks

**Comment by bwagner5** [comment]
Sorry for the delay, eks-charts has been released with the no-schedule on fargate :)

**Comment by limed** [comment]
> Sorry for the delay, eks-charts has been released with the no-schedule on fargate :)

Fantastic, thanks!
