### ISSUE TITLE
[aws-for-fluent-bit] Support for Elastic Search

### ISSUE THREAD

**Issue by michelzanini** [aws/eks-charts#265]
Hi,

Correct me if I am wrong, but it seems that after this [announcement](https://aws.amazon.com/about-aws/whats-new/2020/07/fluent-bit-supports-amazon-elasticsearch-destination-route-container-logs) it's possible to use Fluent Bit to send logs directly to Amazon ElasticSearch.

I am looking for a Helm chart to help configuring Fluent Bit as a DaemonSet and I have seen this chart supports Cloudwatch, Firehose and Kinesis. 

Would it be the case that this chart needs to be updated to add ElasticSearch properties to `values.yaml` to help users configure Fluent Bit to use ElasticSearch?

As I understand, it could be even possible to use this chart to configure ElasticSearch, but it could require more configuration to do so? Any advices on using this or another Helm chart to get this done?

Thanks.

**Comment by allamand** [comment]
Hi @michelzanini, I think it would be nice to include ES logging into this chart!!

Meanwhile, you can find an example working configuration for fluent-bit logging to ES as per the eksworkshop : https://www.eksworkshop.com/intermediate/230_logging/
