### ISSUE TITLE
aws-calico chart 0.3.3 release is missing

### ISSUE THREAD

**Issue by pierluigilenoci** [aws/eks-charts#272]
See above :D

**Comment by pierluigilenoci** [comment]
@jaypipes @limed @casparrolfe Can one of you do something?
Ref: https://artifacthub.io/packages/helm/aws/aws-calico

**Comment by pierluigilenoci** [comment]
@jaypipes any updates?

**Comment by pierluigilenoci** [comment]
Also here https://github.com/aws/eks-charts/issues/281
@kishorj any update?

**Comment by pierluigilenoci** [comment]
Also here https://github.com/aws/eks-charts/issues/201
Maybe some kind of automation to release publicly the charts could be a good idea.

**Comment by jaypipes** [comment]
Apologies, @pierluigilenoci, we delayed the release in order to wait for the new load-balancer-controller v2. We should have the release cut today. So sorry for not communicating properly!

**Comment by pierluigilenoci** [comment]
Don't worry! Good to know. 👍

**Comment by kishorj** [comment]
chart 0.3.4 is now available for aws-calico.

**Comment by pierluigilenoci** [comment]
Thank you
