### ISSUE TITLE
Why is aws-for-fluent-bit memory request 500Mi?

### ISSUE THREAD

**Issue by andrew-e** [aws/eks-charts#277]
Hello,

Out of the box fluent-bit memory request 8Mi per pod, and can probably run on lower, since the point of fluent-bit was to be a low memory solution.  Yet, the values.yaml defaults to 500Mi.  Why is this?  Are you adding 450 mb of dependencies?

Apoogies that this isn't a bug per se, but I am curious to know if I really need to allocate a sizable portion of memory for each node for a log aggregator.

I pulled and ran the Docker image locally, and in an idle state, it has these metrics...
```
CONTAINER ID        NAME                 CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
291cb539e184        optimistic_mestorf   0.01%               25.7MiB / 4.826GiB   0.52%               836B / 0B           0B / 0B             21
```

So, both memory and cpu requests seem excessive.

**Comment by PettitWesley** [comment]
There's an open PR to fix this. The request is too high. As you have seen, in most cases memory usage is quite low.

**Comment by dekarl** [comment]
I think this issue has served its purpose as #323 has since been merged. 🎉
