### ISSUE TITLE
[aws-load-balancer-controller] Question: Why use ECR for image repository ?

### ISSUE THREAD

**Issue by cw-sakamoto** [aws/eks-charts#313]
I look at the [manifest](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_0_0_full.yaml#L480), it maybe specifies dockerhub repository, but here it specifies the ECR. I think it's the same image, but why do you use ECR ?

Either way is fine, but just a confirmation.

**Comment by kishorj** [comment]
Some of the reasons 
- docker hub pull limits
- accessible from private clusters
- easier integration with our code pipeline
- access control via IAM
- reliability
- data transfer cost for the customer (Data transfer between ECR and EC2 in the same region is free of charge, the aws-load-balancer-controller image is available in all regions using the appropriate URL)
...

**Comment by cw-sakamoto** [comment]
@kishorj Thank you for your comment. 
Is there any difference between this and the image in dockerhub?

**Comment by kishorj** [comment]
@cw-sakamoto there should be no difference since both images are built off the same tag. The git commit version is also logged during the controller startup.

**Comment by cw-sakamoto** [comment]
I checked and there was no difference in the commit hash.
