### ISSUE TITLE
[aws-for-fluent-bit] Chart not compatible with kubernetes version 1.18

### ISSUE THREAD

**Issue by Puneeth-n** [aws/eks-charts#318]
The `aws-for-fluent-bit` chart is not compatible with newer version of Kubernetes (1.18)

**Comment by JonathanLachapelle** [comment]
Hi, do you have more details on this? I'm trying to use the chart for the first time on EKS 1.18 and it's not working

**Comment by xposix** [comment]
Latest version is working fine for me today.

**Comment by fawadkhaliq** [comment]
Seems the latest version works fine. Let us know if that's not the case
