### ISSUE TITLE
[aws-load-balancer-controller] Support Setting Environment from Secrets in deployment.yaml

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [aws/eks-charts#325]
In the current version of aws-load-balancer-controller, we are unable to inject AWS credentials from a secret, because the [template](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/deployment.yaml#L91) only supports name/value pairs. 

Given that the values.yaml example is to inject AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as plaintext. We would much rather be able to define as being set from a secret using a "valueFrom" block, rather than a raw "Value" block.

Unfortunately, a change to support that would break existing values.yaml using env as plaintext. Perhaps a new field "rawEnv" or could be appended to the end of the env block in the template?

**Comment by kishorj** [comment]
@AlexMichaelJonesNC, I'm closing this issue. Feel free to report it in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/.
