### ISSUE TITLE
[aws-load-balancer-controller] Upgrade chart to 1.0.5 to reflect additional args

### ISSUE THREAD

**Issue by vmdude** [aws/eks-charts#328]
Actually, the chart doesn't include additional args despite `cluster-name`, `ingress-class`, `aws-region` and `aws-vpc-id` as seen at https://github.com/aws/eks-charts/blob/f19329d8f674646ece6b3712303b0284ebe4a0bf/stable/aws-load-balancer-controller/templates/deployment.yaml#L40-L50

On the master branch, the chart support additional args, as seen at https://github.com/aws/eks-charts/blob/038e115b08e5f345fe1620dca0b8da4da78c6e75/stable/aws-load-balancer-controller/templates/deployment.yaml#L40-L90

Steps to reproduce this behavior:

```
$ helm repo add eks https://aws.github.io/eks-charts
$ helm repo update
$ helm search repo eks/aws-load-balancer-controller
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
eks/aws-load-balancer-controller	1.0.4        	v2.0.0     	AWS Load Balancer Controller Helm chart for Kub...

$ helm template eks/aws-load-balancer-controller --values values.yaml
```

The produced deployment will be based on version `1.0.4`(which is tagged `v0.0.32`), missing the PR https://github.com/aws/eks-charts/pull/312

**Comment by kishorj** [comment]
New chart 1.0.5 has just been released. Closing this issue.
