### ISSUE TITLE
Change imagePullPolicy to IfNotPresent

### ISSUE THREAD

**Issue by nzoueidi** [aws/eks-charts#333]
Changing imagePullPolicy to IfNotPresent instead of Always, so we prevent extra latency and delay on EKS bootstrapping  and load on ECR. 

xref: https://github.com/aws/amazon-vpc-cni-k8s/issues/1249

**Comment by jdn5126** [comment]
Since the VPC-CNI image specifies a tag that is not `latest`, the image pull policy is set to `IfNotPresent` by default. Closing this as resolved.
