### ISSUE TITLE
examples would be helpful

### ISSUE THREAD

**Issue by rojomisin** [aws/eks-charts#334]
the configuration via helm lists the configuration options, but fails to provide even 1 example, this would be helpful, especially when trying to use `serviceAccount.annotations`

**Comment by bwagner5** [comment]
is this a general issue about all charts in this repo or a specific chart?

**Comment by rojomisin** [comment]
oh my bad, yes thinking of https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

**Comment by alvarodelvalle** [comment]
@rojomisin 
does this help? 
```hcl
resource "helm_release" "lb_controller" {
  depends_on = [aws_iam_role.lb_controller]
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  name       = var.project

  values = [<<EOF
clusterName: ${var.cluster_name}
region: ${data.aws_region.current.name}
vpcId: ${var.vpc_id}
hostNetwork: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${aws_iam_role.lb_controller.arn}
EOF
  ]
}
```

**Comment by rojomisin** [comment]
hi @alvarodelvalle kind of, not using terraform for this atm, but it was more of helm usage for EKS on aws, because in their docs they list all these manual steps which ok it might work for some, but to automate it one has to try and do something like:
- install controller
- configure rbac to a role arn
- create service account
- link rbac role to service account

```
	@$(HELM) upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
		--set clusterName=$(call get-resource-by-name,$(EKS_CLUSTER_STACKNAME),EKSCluster) \
  		--set serviceAccount.create=false \
  		--set serviceAccount.name=alb-ingress-controller \
  		--set rbac.create=true \
  		--set region=$(AWS_REGION) \
		--set vpcId=$(VPC_ID) \
  		--namespace kube-system
```

what's the syntax for annotations? i found this https://stackoverflow.com/questions/59632924/how-to-set-annotations-for-a-helm-install

my hope is that aws improves their eks docs and not rely on manual and/or eksctl based solutions

**Comment by rojomisin** [comment]
yeah so it works, creates the rbac clusterrole and seviceaccount correctly now, but I cannot figure out the syntax for the `serviceAccount.annotation=` 
```
	@$(HELM) upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
		--set clusterName=$(call get-resource-by-name,$(EKS_CLUSTER_STACKNAME),EKSCluster) \
  		--set serviceAccount.create=true \
  		--set serviceAccount.name=aws-load-balancer-controller \
  		--set rbac.create=true \
  		--set region=$(AWS_REGION) \
		--set vpcId=$(VPC_ID) \
  		--namespace kube-system
```

I would like to be able to not do this command too afterwards
```
	@$(KUBECTL) annotate serviceaccount -n kube-system aws-load-balancer-controller \
		eks.amazonaws.com/role-arn=arn:aws:iam::$(AWS_ACCOUNT):role/aws-load-balancer-controller-$(call get-resource-by-name,$(EKS_CLUSTER_STACKNAME),EKSCluster) --overwrite
```

**Comment by Justin-DynamicD** [comment]
Stumbled on this and used your links to get this right.

Those looking for annotations: if you are setting from cmdline and not fro ma yaml, you need to be sure to comment out those dots "\." or yaml will atempt to nest things morethan is should.  Example:

```
helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system \
--set clusterName=my_eks_cluster \
--set serviceAccount.create=true \
--set serviceAccount.name=aws-load-balancer-controller \
--set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::123456789012:role/myrole"
```

role names changed to protect the innocent.

**Comment by kishorj** [comment]
@rojomisin, I'm closing the issue. If you have further concerns, please file an issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/
