### ISSUE TITLE
Add CNI metrics helper to the aws-vpc-cni chart

### ISSUE THREAD

**Issue by max-rocket-internet** [aws/eks-charts#34]
Would be good to have a chart for this also: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/cni-metrics-helper.yaml

**Comment by stefanprodan** [comment]
@max-rocket-internet I think this could be part of the CNI chart as an opt-in component e.g.
```
helm install aws-vpc-cni eks/aws-vpc-cni --namespace kube-system \
--set metricsHelper.enabled=true
```

**Comment by max-rocket-internet** [comment]
Yeah makes more sense 👍

**Comment by abdennour** [comment]
Yep. Any deadline ?

**Comment by max-rocket-internet** [comment]
I don't think anyone is working on this. Feel free to a make a PR though.

**Comment by max-rocket-internet** [comment]
Refer to https://github.com/aws/eks-charts/issues/155 and there's no a PR.
