### ISSUE TITLE
Missing EKS helm charts

### ISSUE THREAD

**Issue by yanivpaz** [aws/eks-charts#354]
It will be very useful to have e2e list of helm charts in this repository
like [here ](https://github.com/yanivpaz/yanivpaz.github.io/blob/master/_posts/markdowns/eks-posts-deployment.md)
example for missing charts in this repo 
- cluster auto scalar 
- external dns 
- csi for ebs/efs

**Comment by stevehipwell** [comment]
I'd add the following charts as being wanted.

- _kube-proxy_
- _CoreDNS_

**Comment by max-rocket-internet** [comment]
@yanivpaz 

cluster-autoscaler is here: https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler
external-dns is here: https://github.com/bitnami/charts/tree/master/bitnami/external-dns

@stevehipwell 

coredns is here: https://github.com/coredns/helm

**Comment by stevehipwell** [comment]
@max-rocket-internet I'm pretty sure there is an open issue that the CoreDNS chart can't be used to set the correct values for EKS but I'd be very happy to be proved wrong?

On a separate note the _external-dns_ chart you've linked to is a Bitnami one so it's not using the Kubernetes built images; I offered to write a chart for the maintainers but they declined however I think there is still the need for a chart based on the official image and config.

**Comment by pierluigilenoci** [comment]
Also csi-secrets-store-provider-aws is missing.
Ref: https://github.com/aws/eks-charts/issues/633 and https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35

**Comment by pierluigilenoci** [comment]
csi-secrets-store-provider-aws helm chart is released.

**Comment by bryantbiggs** [comment]
thank you all - closing this out since nearly all of these now have publicly available charts
