### ISSUE TITLE
CRDs fail to install

### ISSUE THREAD

**Issue by adamkgray** [aws/eks-charts#359]
I am installing the aws load balancer for the first time and the documentation says to do this before installing the helm chart:

```
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
```

But the command never returns. There is no output. It just hangs forever. Is this local issue or a CDN issue?

**Comment by bwagner5** [comment]
I just tried it and it worked for me, so probably a local issue.

**Comment by modevops** [comment]
does not work for me   $ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}


I am tired of devs ignoring users please fix

**Comment by kishorj** [comment]
@modevops did you try with a new version of kubectl?

**Comment by kishorj** [comment]
@adamkgray, I'm closing the issue. If you have further concerns on this matter, please open a new issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller.
