### ISSUE TITLE
[aws-load-balancer-controller] POD crashing on a Fargate-only cluster

### ISSUE THREAD

**Issue by kishoreallwynraj** [aws/eks-charts#376]
I have created an Fargate-only cluster, so my “default” and “kube-system” resources are also part of fargate profile. Now when I try to follow the setup of the ALB controller by running the helm cammand, I see the POD is going to “CrashLoopBackoff”. I checked the POD logs and I found this error. Is this issue due to cluster been created as an Fargate-only cluster?. Does the ALB has to be installed in a namespace which runs on EC2 instance?
```
unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: RequestError: send request failed
caused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

**Comment by kishorj** [comment]
@kishoreallwynraj, The AWS Load Balancer controller can be installed on Fargate-only namespace, you'd need to specify the region and vpc id during helm installation. If AWS_REGION and VPC_ID env variables point to the region and the vpc id, you'd need to add the following arguments to the helm installation command - 
```
  	--set region=$(AWS_REGION) --set vpcId=$(VPC_ID)
```

**Comment by kishorj** [comment]
@kishoreallwynraj, Closing the issue. Feel free to reopen if the problem still exists.
