### ISSUE TITLE
[aws-load-balancer-cotroller] Set limits and requests in the helm chart by default

### ISSUE THREAD

**Issue by rothgar** [aws/eks-charts#380]
It would be good practice to have some default limits for the controller. Have we benchmarked it to have an idea of ideal usage?

If we have some numbers I can PR the chart to add defaults and make them configurable.

**Comment by kishorj** [comment]
@rothgar Feel free to raise a PR based on the limits from https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_1_0_full.yaml

**Comment by rothgar** [comment]
Looking at the chart there's a note that having default limits isn't desired.

https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml#L46

I guess I can close this request and we can reevaluate in the future if people ask for it.
