### ISSUE TITLE
[aws-load-balancer-controller ] misleading/outdated documentation

### ISSUE THREAD

**Issue by joncolby** [aws/eks-charts#381]
The README explains that the CRD should be installed as a seperate step using `kubectl`.  However,  the [chart layout](https://helm.sh/docs/topics/charts/#the-chart-file-structure) is such that the CRDs will be automatically installed (with helm3).

```
Install the TargetGroupBinding CRDs:

kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
```

**Comment by kishorj** [comment]
The chart version is v2, so the crds will not be installed automatically. The documentation is correct.

**Comment by zxkane** [comment]
@kishorj any reason why not putting the CRDs also in the Helm chart? I checked the chart it does not use the CRDs kinds(TargetGroupBinding/TargetGroupBindingList).

We’re using IaC(cdk/cdk8s) to manage the EKS and ALB controller. It’s required using additional **kustomize** cmd to install CRD into the EKS cluster which is not supported by cdk.

**Comment by kishorj** [comment]
Refer to the comment https://github.com/aws/eks-charts/issues/374#issuecomment-741806799.
