### ISSUE TITLE
aws-cni-1.1.1 does not exist

### ISSUE THREAD

**Issue by mohsen0** [aws/eks-charts#385]
Hi 
can you release the artifact of aws-cni-1.1.1?

https://github.com/aws/eks-charts/find/gh-pages
![Screenshot 2020-12-10 at 23 23 04](https://user-images.githubusercontent.com/135178/101841888-c68be480-3b3e-11eb-9a3b-916e6301bbe9.png)

https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/Chart.yaml#L3

**Comment by max-rocket-internet** [comment]
Exactly. We are also waiting for this release.

The real problem is covered in https://github.com/aws/eks-charts/issues/53

**Comment by jayanthvn** [comment]
Hi @mohsen0 

I do see aws-vpc-cni-1.1.1 artifact now attached. Also the latest 1.1.3 is available. So closing the issue.
