### ISSUE TITLE
Docker Image not available in other region - ImagePullBackOff error

### ISSUE THREAD

**Issue by toytown** [aws/eks-charts#386]
When using helm chart to deploy the ALB, in region eu-central-1 it is trying to download the image repository from 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller as stated in the ALB documentation

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
--set clusterName=eks-demo-tefde \
--set serviceAccount.create=true \
--set serviceAccount.name=aws-load-balancer-controller \
--set vpcId=vpc-079a7af980eb3957e \
-n kube-system

After some tries trying to pull images the container backoffs. This is mainly due to firewall rules in the enterprise setup which does not allow connection to the 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller

![image](https://user-images.githubusercontent.com/535868/101931158-567e6c80-3bd9-11eb-96a4-98757a3f3da5.png)

**Comment by kishorj** [comment]
You need to use the image `602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.0`. We've posted the image across all regions. You can specify the following additional arguments to the helm upgrade command 

`--set image.repository=602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon/aws-load-balancer-controller --set image.tag=v2.1.0`

Let us know if you still encounter issues.

**Comment by kishorj** [comment]
@toytown, if you still encounter issues, let us know. I'm closing the issue for now.

**Comment by toytown** [comment]
Thanks yes this helped  and solved the issue

**Comment by damianarata** [comment]
Hey @kishorj , where I can found the list of images? I'm searching this on in us-east-1. Thanks!

**Comment by kishorj** [comment]
@damianarata, You can find the list of images in the release notes. For v2.2.1 release, https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.2.1 in the "ECR images" section. 

602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-load-balancer-controller:v2.2.1
