### ISSUE TITLE
Cross VPC k8s resource adding in Tagrget Group

### ISSUE THREAD

**Issue by kapendrasingh** [aws/eks-charts#392]
Hi

i have an EKS TG(will refer as k8s-TG) and another ip based new TG in a different VPC in the same region(will refer as new-TG).

i did VPC peering and getting an error

{"level":"error","ts":1607958641.8023963,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"elbv2.k8s.aws","reconcilerKind":"TargetGroupBinding","controller":"targetGroupBinding","name":"ab-dev-new-TG","namespace":"dev","error":"ValidationError: The Availability Zone for IP address '10.0.3.84' must be 'all' for Application Load Balancer target groups, when not within the VPC\n\tstatus code: 400, request id: 1627813a-d86e-4dac-ab3b-2d60ff37ac85"}

i am expecting pod IP must be populated in is new-TG same as k8s-TG  (same k8s service is referred in both)

**Comment by M00nF1sh** [comment]
Hi, i don't support bind to TG in another vpc yet, which will be supported in next minor version soon

**Comment by kishorj** [comment]
Closing the issue since we are already tracking it in the upstream repo https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2650
