### ISSUE TITLE
appmesh-controller fails with terraform-kubernetes-alpha

### ISSUE THREAD

**Issue by AndyMoore** [aws/eks-charts#402]
same issue as per https://github.com/banzaicloud/istio-operator/issues/445 - the controller fails with the following error:

```Error: rpc error: code = Unknown desc = update dry-run for '/mesh1' failed: admission webhook "mmesh.appmesh.k8s.aws" does not support dry run```

I believe this could/should be remedied by setting `sideEffects: None` within https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/templates/webhook.yaml

**Comment by achevuru** [comment]
@AndyMoore Are you using K8S v1.19+?  "sideEffects" is now a mandatory field for Webhooks in 1.19+ and we need to specify it. This [PR ](https://github.com/aws/eks-charts/pull/403)will introduce the relevant changes required for 1.19+ clusters for AppMesh controller. Right now, EKS doesn't support K8S v1.19 yet.

**Comment by achevuru** [comment]
@AndyMoore 1.19 is already out and you should be able to use the latest charts with v1.19. Closing the issue now, feel free to open if you run in to any other issues.
