### ISSUE TITLE
Webhook prevents deploying multiple ingress resources

### ISSUE THREAD

**Issue by rokarajan** [aws/eks-charts#405]
Looks like this thread is open so wanted to ask few questions:

- We have multiple ingress controllers deployed with old(now deprecated incubator/aws-alb-ingress-controller) helm chart and they serve different purposes.

- We have migrated one of the controller with the new chart aws-load-balancer-controller from eks-charts repo however we came across an issue that prevents deploying the second controller. Thats because the webhook name(i.e. aws-load-balancer-webhook) cannot be changed for different controllers in different namespace. Is there a way we can get some flexibility on updating the name via values so that they get reflected to corresponding release names?

- we would like to use existing LBs where possible.

**Comment by kishorj** [comment]
The current release of AWS load balancer controller does not support running multiple controller instances in the same cluster, there are issues with the NLB-IP feature and management of security group rules. 

The new controller does not have scalibility or AWS throttling issues and you can use it for all ingresses in your cluster. Could you share your use case in more detail that would require multiple controllers?

**Comment by rokarajan** [comment]
Thanks for your reply @kishorj !
- We have multiple load balancers to serve varieties of traffic ( some service specific, private, public etc), with our current setup we have different sets of alb ingress controllers deployed in different namespace handling them. We also use NGINX ingress controllers for the services so that we could run multiple services under one ALB. Only the problem we have is the current helm chart i.e incubator is deprecated.

**Comment by kishorj** [comment]
@rokarajan, the version 1.x and the corresponding incubator chart is deprecated, and is no longer under active development. For the current v2 release, we don't currently support running multiple controllers in the same cluster and don't have immediate plans to do so.

We recommend running only one AWS load balancer controller in your cluster to reconcile all supported ingresses in your cluster. Please share any issues you run into with this approach.

**Comment by kishorj** [comment]
@rokarajan closing the issue for now. Feel free to open a new issue.
