### ISSUE TITLE
[aws-load-balancer-controller] repository requires authentication

### ISSUE THREAD

**Issue by Justin-DynamicD** [aws/eks-charts#420]
Currently, the aws-load-balancer-controller is hosted on `us-west-2` in this repo:

`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller`

The problem is this repo requires authentication.  This is fine for some clients in general AWS ... but clients in a gov location like `us-gov-west-1` are logged into an isolated cloud and thus the eks cluster can't download the image to run.

Other charts in this collection are on anonymous repos that can be downloaded from without complication, and it would be nice if we could have similar behavior.

**Comment by kishorj** [comment]
@Justin-DynamicD Check if your worker node instance role grants ECR access permissions. We post the images across all available regions, here is the release note link for [2.1.1 release](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.1.1) which contains all the ECR locations. You should be able to specify the image location during installation.

Here is an example to download v2.1.1 from govcloud
```
helm upgrade  aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system  --set clusterName=<your cluster name>  --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set image.repository=013241004608.dkr.ecr.us-gov-west-1.amazonaws.com/amazon/aws-load-balancer-controller --set image.tag=v2.1.1
```

**Comment by Justin-DynamicD** [comment]
Yes it allows ECR, my current workaround is I pushed the container into an ECR hosted in my tenant :)

Thank you for the list of available endpoints, I'll try it when I get a moment

**Comment by Justin-DynamicD** [comment]
I will close this issue as I was unaware this replicated into gov cloud.  Thank you for enlightening me on this fact!
