### ISSUE TITLE
[aws-vpc-cni] Helm install failed, due to missing required annotation for CRD metadata

### ISSUE THREAD

**Issue by jennieli-els** [aws/eks-charts#421]
Helm 3 doc about helm labels and annotations: https://helm.sh/docs/chart_best_practices/labels/

Logs for helm install:
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "eniconfigs.crd.k8s.amazonaws.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aws-vpc-cni"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"`

**Comment by jayanthvn** [comment]
Hi @jennieli-els 

Was the previous install of ENIConfig CRD done manually and then followed by helm upgrade? Because the error shows - "resource that already exists".

**Comment by jayanthvn** [comment]
Hi @jennieli-els 

Can you please confirm if the CRD was manually installed first?

**Comment by skasukur** [comment]
Hi @jayanthvn 

I am also getting the same issue. I have just created the cluster and added aws-auth config map. I haven't created any resources on Kubernetes cluster. 

EKS Kubernetes version - 1.19

Please let me know if you need more information.

**Comment by arthurbdiniz** [comment]
Hi guys,

Having the same issue.

I could manage to fix following this instructions:

#### Adopting the existing aws-node resources in an EKS cluster
If you do not want to delete the existing aws-node resources in your cluster that run the aws-vpc-cni and then install this helm chart, you can adopt the resources into a release instead. This process is highlighted in this [PR comment](https://github.com/aws/eks-charts/issues/57#issuecomment-628403245). Once you have annotated and labeled all the resources this chart specifies, enable the `originalMatchLabels` flag, and also set `crd.create` to false on the helm release and run an update. If you have been careful this should not diff and leave all the resources unmodified and now under management of helm.

Here is an example script to modify the existing resources:

WARNING: Substitute YOUR_HELM_RELEASE_NAME_HERE with the name of your helm release.

```bash
#!/usr/bin/env bash

set -euo pipefail

# don't import the crd. Helm cant manage the lifecycle of it anyway.
for kind in daemonSet clusterRole clusterRoleBinding serviceAccount; do
  echo "setting annotations and labels on $kind/aws-node"
  kubectl -n kube-system annotate --overwrite $kind aws-node meta.helm.sh/release-name=YOUR_HELM_RELEASE_NAME_HERE
  kubectl -n kube-system annotate --overwrite $kind aws-node meta.helm.sh/release-namespace=kube-system
  kubectl -n kube-system label --overwrite $kind aws-node app.kubernetes.io/managed-by=Helm
done
```

**Comment by github-amine-kherbouche** [comment]
The missing part is to annotate/label the CRD `eniconfigs.crd.k8s.amazonaws.com` with:
```
kubectl -n kube-system annotate --overwrite crd eniconfigs.crd.k8s.amazonaws.com meta.helm.sh/release-name="$HELM_RELEASE_NAME"
kubectl -n kube-system annotate --overwrite crd eniconfigs.crd.k8s.amazonaws.com meta.helm.sh/release-namespace=kube-system
kubectl -n kube-system label --overwrite crd eniconfigs.crd.k8s.amazonaws.com app.kubernetes.io/managed-by=Helm
```

That can help the install of the helm chart

**Comment by nwilliams-lw** [comment]
For terraform users:
The kubernetes provider has added [kubernetes_labels](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/labels) and [kubernetes_annotations](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/annotations) which allow patching of the labels and annotations. 

This should clean up the use of this module as we can patch the resources prior to applying the helm chart via the helm provider. However there is a bug in the kubernetes provider that means patches to the labels will override changes to the annotations: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1690

Once that bug is fixed something like this should work:

```
locals {
  kinds = {
    "DaemonSet": {
      api_version: "apps/v1",
      name: "aws-node",
      namespace: "kube-system"
    },
    "ClusterRole": {
      api_version: "rbac.authorization.k8s.io/v1",
      name: "aws-node",
      namespace: null
    },
    "ClusterRoleBinding": {
      api_version: "rbac.authorization.k8s.io/v1",
      name: "aws-node",
      namespace: null
    },
    "CustomResourceDefinition": {
      api_version: "apiextensions.k8s.io/v1",
      name: "eniconfigs.crd.k8s.amazonaws.com",
      namespace: null
    }
    "ServiceAccount": {
      api_version: "v1",
      name: "aws-node",
      namespace: "kube-system"
    }
  }
}

resource "kubernetes_labels" "cni_helm_ownership_patch" {
  for_each = local.kinds

  api_version = each.value.api_version
  kind        = each.key
  metadata {
    name = "aws-node"
    namespace = each.value.namespace
  }
  labels = {
    "app.kubernetes.io/managed-by" = "Helm"
  }
}

resource "kubernetes_annotations" "cni_helm_ownership_patch" {
  for_each = local.kinds

  api_version = each.value.api_version
  kind        = each.key
  metadata {
    name = each.value.name
    namespace = each.value.namespace
  }
  annotations = {
    "meta.helm.sh/release-name" = "aws-vpc-cni",
    "meta.helm.sh/release-namespace" = "kube-system"
  }
}

resource "helm_release" "aws_vpc_cni" {
  # required to update an immutable field on the daemonset, avoids:
  # "Invalid value: ... field is immutable"
  force_update = true
  name             = "aws-vpc-cni"
  namespace        = "kube-system"
  chart            = "aws-vpc-cni"
  version          = "1.1.16"
  repository       = "https://aws.github.io/eks-charts"
  max_history      = 5
  atomic           = true
  cleanup_on_fail  = true
  create_namespace = true

  depends_on = [
    kubernetes_labels.cni_helm_ownership_patch,
    kubernetes_annotations.cni_helm_ownership_patch,
  ]
}

```

**Comment by herculan0** [comment]
Does someone know how to fix this with CDK eks.Cluster.addHelmChart ?

**Comment by a0s** [comment]
I've got this error when try to install `aws-vpc-cni` into fresh eks cluster with no addons.
Solutions from @arthurbdiniz and @github-amine-kherbouche are still actual.

**Comment by atamgp** [comment]
same issue here. EKS cluster using the TF module, no cni addon, but this issue when installing the helm chart.

**Comment by jdn5126** [comment]
This should be resolved once https://github.com/aws/amazon-vpc-cni-k8s/pull/2144 and a new release is cut

**Comment by seetamraju** [comment]
You'll find the following in official EKS instructions/documentation.
This fixed all eniconfigs issues for me!

```
HELM_RELEASE_NAME="aws-vpc-cni"

for kind in daemonSet clusterRole clusterRoleBinding serviceAccount; do
    echo "	setting annotations and labels on $kind/aws-node"
    kubectl -n kube-system annotate --overwrite $kind aws-node meta.helm.sh/release-name=${HELM_RELEASE_NAME} --context "${KUBECTL_CONTEXT}"
    kubectl -n kube-system annotate --overwrite $kind aws-node meta.helm.sh/release-namespace=kube-system --context "${KUBECTL_CONTEXT}"
    kubectl -n kube-system label --overwrite $kind aws-node app.kubernetes.io/managed-by=Helm --context "${KUBECTL_CONTEXT}"
done
```

**Comment by jdn5126** [comment]
Closing as move to `crds` folder has happened in latest chart
