### ISSUE TITLE
[aws-load-balancer-controller] Unable to create  a second controller within the same namespace

### ISSUE THREAD

**Issue by e-jjj** [aws/eks-charts#430]
Hello,

I'm unable to install a second aws load balancer controller within the same namespace where a controller already exists. This is required in order to use different ingress classes in the ingress resources pointing to two different application load balancers. I get the following error when I try to install the additional aws load balancer controller via helm,

```
helm upgrade -i aws-load-balancer-controller-qa eks/aws-load-balancer-controller -n devops-apps --set clusterName=eks-xxxx --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller-qa --set ingressClass=alb-qa

Release "aws-load-balancer-controller-qa" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "aws-load-balancer-tls" in namespace "devops-apps" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "aws-load-balancer-controller-qa": current value is "aws-load-balancer-controller"
```
The name of the existing controller is aws-load-balancer-controller. 
It looks like the tls secret can not be shared across controllers with different names?

If installing an additional controller under the same namespace is not possible, can someone please point me in the right direction. How can additional application load balancers be created with the single controller?

Thanks

**Comment by terranisu** [comment]
@e-jjj it's possible. you can override the name of the controller with the `"nameOverride"` setting and it will create a different set of Kubernetes objects under the same namespace.

**Comment by kishorj** [comment]
@e-jjj The current AWS load balancer controller does not support running multiple controller deployments in the same kuernetes cluster. There are issues with NLB-IP feature and management of security group rules. Since there are no scalability or AWS throttling issues, you should be able to use the single controller for all of your ingresses in your cluster. Any use-case you have that we don't support currently?

**Comment by e-jjj** [comment]
@kishorj we need to have multiple ALBs to support different app environments within the namespace. To support more apps and the different environments, we don't want to have a single aws load balancer controller set with a single ingress class but use multiple ingress classes, we have hit the limits with the number of listener rules in the application load balancers when running multiple environments in the single alb.  I currently run two ALBs within the same cluster in two different namespaces, it provisioned ok and it seems to work fine.   
However we dont want to run controllers in different namespaces but use a single namespace for all the controllers supporting the different apps in the different environments. 
Can i have a single controller and create multiple application load balancers?
