### ISSUE TITLE
[aws-load-balancer-controller] Error: UPGRADE FAILED: failed to replace object Service aws-load-balancer-webhook-service is invalid: spec.clusterIP

### ISSUE THREAD

**Issue by aviorma** [aws/eks-charts#438]
**Describe the bug**
A concise description of what the bug is.

Upgrade an existing helm (helm3) release with existing ClusterIP for aws-load-balancer-webhook-service
from prior deployed release 

Error: UPGRADE FAILED: failed to replace object: Service \"aws-load-balancer-webhook-service\" is invalid: spec.clusterIP: Invalid value: \"\": field is immutable

**Steps to reproduce**

1. Create eks 
2. Attach IAM role for ALB
3. Install aws load balancer helm chart 
4. upgrade aws load balancer helm chart

**Expected outcome**
release upgraded successfully 

A concise description of what you expected to happen.

**Environment**

EKS 1.17

* Chart name: aws-load-balancer-controller
* Chart version: v2.1.1
* Kubernetes version: v1.17.12-eks-7684af
* Using EKS (yes/no), if so version? yes 

**Additional Context**:

**Comment by kishorj** [comment]
@aviorma, please provide the following details - 
- What is your helm version - `helm version`?
- What is the chart version you had installed in step 3, and the chart version you are trying to upgrade to?
- Helm install/upgrade commands used in step 3 and 4

**Comment by aviorma** [comment]
What is your helm version - helm version? `3.4.2`
What is the chart version you had installed in step 3, and the chart version you are trying to upgrade to? `1.1.2`
Helm install/upgrade commands used in step 3 and 4? `1.1.3`

**Comment by aviorma** [comment]
Helm commands 

Install aws-load-balancer-controller-1.1.2

> helm upgrade --install --force aws-load-balancer-controller ./aws-load-balancer-controller-1.1.2.tgz --set clusterName=${EKS_CLUSTER_NAME} --set region=${AWS_REGION) --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller  --namespace kube-system --install --cleanup-on-fail


Upgrade to aws-load-balancer-controller-1.1.3

> helm upgrade --install --force aws-load-balancer-controller ./aws-load-balancer-controller-1.1.3.tgz --set clusterName=${EKS_CLUSTER_NAME} --set region=${AWS_REGION) --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller  --namespace kube-system --install --cleanup-on-fail

**Comment by SagurovA93** [comment]
Just ran into this issue.

The Helm version - "v3.5.3"
The EKS version - "1.18"
aws-load-balancer-controller version - "v2.1.3"

The same happening with the **aws-load-balancer-webook-service**:
`Error: an error occurred while rolling back the release. original upgrade error: failed to replace object: Service "aws-load-balancer-webhook-service" is invalid: spec.clusterIP: Invalid value: "": field is immutable: failed to replace object: Service "aws-load-balancer-webhook-service" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

**Comment by kishorj** [comment]
Possible due to the `--force` option in helm install.

For further reference - https://github.com/helm/helm/issues/7956

**Comment by kishorj** [comment]
@SagurovA93, could you confirm you did not use the `--force` option?
@aviorma, are you able to install without the `--force` option?

**Comment by SagurovA93** [comment]
@kishorj yes, I used the `force_update` option from the terraform provider [helm_release](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#force_update).

**Comment by kishorj** [comment]
closing since it is an issue with helm not this specific chart.

**Comment by aviorma** [comment]
it is reproduced, guys 

`Service "aws-load-balancer-webhook-service" is invalid: [spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset`

**Comment by aviorma** [comment]
please reopened it

**Comment by aviorma** [comment]
Possible fix in the service type on the chart 

` clusterIP: "{{ .Values.service.clusterIP }}"`

**Comment by PeterSzegedi** [comment]
This issue also affects aws-calico

**Comment by kishorj** [comment]
I'm closing the issue. If problem persists, please file it in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/
