### ISSUE TITLE
Failed to create LoadBalancer for EKS Fargate cluster

### ISSUE THREAD

**Issue by hardillb** [aws/eks-charts#447]
**Describe the bug**
While trying to create a load balancer on a fresh EKS Fargate cluster I get the following error on the last step of the instructions:

```$ kubectl apply -f v2_1_0_full.yaml 
customresourcedefinition.apiextensions.k8s.io/targetgroupbindings.elbv2.k8s.aws created
mutatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook created
role.rbac.authorization.k8s.io/aws-load-balancer-controller-leader-election-role created
clusterrole.rbac.authorization.k8s.io/aws-load-balancer-controller-role created
rolebinding.rbac.authorization.k8s.io/aws-load-balancer-controller-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/aws-load-balancer-controller-rolebinding created
service/aws-load-balancer-webhook-service created
deployment.apps/aws-load-balancer-controller created
validatingwebhookconfiguration.admissionregistration.k8s.io/aws-load-balancer-webhook created
Error from server (InternalError): error when creating "v2_1_0_full.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: no endpoints available for service "cert-manager-webhook"
Error from server (InternalError): error when creating "v2_1_0_full.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: no endpoints available for service "cert-manager-webhook"
```
And when I run `kubectl get deployment -n kube-system aws-load-balancer-controller` the load balancer shows an unavailable

**Steps to reproduce**
Follow the instructions in the following page
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html

At step 6 choose the "With a Kubernetes manifest" option.

This is a kubenetes v1.18 so pick the first `kubectrl` command which completes cleanly.

After editing the v1_2_0_full.yaml to remove:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
  namespace: kube-system
```
And replace ` --cluster-name=your-cluster-name` with  ` --cluster-name=node-red` where my cluster is named `node-red`

running `kubectrl apply -f v1_2_0_full.yaml` give the error in the description

**Expected outcome**
I expect no error and when running `kubectl get deployment -n kube-system aws-load-balancer-controller` I expect to see the `aws-load-balancer-controller` to be marked as available as described in the documentation.

**Environment**

* Chart name: NA
* Chart version: NA
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? yes eks.3

**Additional Context**:
It was suggested I raise this here by @AWSSupport on Twitter https://twitter.com/AWSSupport/status/1357737334612127745

I've attached my edited v1_2_0_full.yaml

[v2_1_0_full.yaml.txt](https://github.com/aws/eks-charts/files/5934303/v2_1_0_full.yaml.txt)

**Comment by kishorj** [comment]
@hardillb, Cert-manager does not run on Fargate. So, you'd need to install the helm chart from this repo instead of applying the manifest directly.

You can refer to https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller for further instructions. If you are running the controller in Fargate, you'd need to specify the region and vpc id during helm installation. If AWS_REGION and VPC_ID env variables point to the region and the vpc id, you'd need to add the following arguments to the helm installation command -

```
  	--set region=$(AWS_REGION) --set vpcId=$(VPC_ID)
```
Before installing helm chart, make certain you remove the previous applied v2.1.0 manifest.

**Comment by hardillb** [comment]
OK, thanks for pointing that out.
Can I suggest that the documentation I linked to is updated to point that out, as there is nothing to say that only the Helm version will work with a Fargate based cluster.

**Comment by kishorj** [comment]
@hardillb, thanks for the suggestion. PR https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1805/ in the upstream repository points out this fact in the installation instructions. Closing this issue.
