### ISSUE TITLE
[aws-load-balancer-controller] Supporting sidecar containers in helm chart

### ISSUE THREAD

**Issue by nanasi880** [aws/eks-charts#450]
**Is your feature request related to a problem?**
I am hosting aws-load-balancer-controller with EKS Fargate.
DaemonSet does not work on EKS Fargate, so I need to run this as a sidecar container.
Being able to enter the sidecar container as a parameter, like prometheus, is very useful in this case.

https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L565
https://github.com/helm/charts/blob/master/stable/prometheus/templates/deployments/server.yaml#L149-L151

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-load-balancer-controller

**Describe the solution you'd like**
The ability to freely injection sidecar containers, like the helm chart in prometheus.

**Describe alternatives you've considered**
I can use the `helm template` command or use `kustomize` in the post renderer to merge the results, but it is better to have native support.

**Comment by kishorj** [comment]
@nanasi880, I'm closing the issue. If you have further concerns, please file an issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/

**Comment by nanasi880** [comment]
OMG
It is clear that this is a problem with the Helm chart and not with LoadBalancerController itself.
It is not an upstream software issue, it just changes the rendering of the Helm chart.

**Comment by kishorj** [comment]
@nanasi880, the helm chart is also part of the upstream repository. At the time of the release, we sync the chart from the upstream repo to eks-charts.
