### ISSUE TITLE
aws-vpc-cni: Add podLabels parameter to aws-vpc-cni chart

### ISSUE THREAD

**Issue by leandrocostam** [aws/eks-charts#457]
**Is your feature request related to a problem?**
We manage/parse logs from Kubernetes containers using a mix of labels and annotations. We are not able to add any custom label to aws-vpc-cni pods, only annotations by using `podAnnotations` parameter.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-vpc-cni

**Describe the solution you'd like**
I would like to add custom labels to aws-vpc-cni pods by using `podLabels` parameter.

**Comment by jayanthvn** [comment]
Hi,

Thanks for opening the issue, please feel free to open a PR.

**Comment by leandrocostam** [comment]
@jayanthvn PR was created along with this issue: #458

**Comment by jayanthvn** [comment]
Thank you @leandrocostam

**Comment by jayanthvn** [comment]
Merged #458
