### ISSUE TITLE
aws-calico: Add podLabels parameter to aws-calico chart 

### ISSUE THREAD

**Issue by leandrocostam** [aws/eks-charts#459]
**Is your feature request related to a problem?**
We manage/parse logs from Kubernetes containers using a mix of labels and annotations. We are not able to add any custom label to aws-calico pods, only annotations by using `podAnnotations` parameter.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-calico

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
I would like to add custom labels to aws-calico pods by using `podLabels` parameter.

**Comment by jayanthvn** [comment]
Hi @leandrocostam 

Thanks for opening the issue, please feel free to open a PR.

**Comment by leandrocostam** [comment]
@jayanthvn PR #460 was created along with this issue.

**Comment by jayanthvn** [comment]
Thank you @leandrocostam

**Comment by jayanthvn** [comment]
Merged #460
