### ISSUE TITLE
[aws-node-termination-handler] Add 0.3.0 Chart to Repository Index

### ISSUE THREAD

**Issue by mrkwtz** [aws/eks-charts#46]
Hey,

right now the latest chart version in your repo for the "aws-node-termination-handler" is 0.2.0. The master branch is on version 0.3.0 but this version is nowhere to be found.

The 0.2.0 version does not align with your chart description on master, because in the 0.2.0 chart you use .Values.namespace to set the namespace for the subject in the clusterrolebinding. In the 0.3.0 values description this is not mentioned and the 0.3.0 chart uses (rightfully so) the .Release.Namespace value.

**Comment by max-rocket-internet** [comment]
See https://github.com/aws/eks-charts/issues/36

**Comment by mrkwtz** [comment]
Thx. @nckturner could you add a tag to trigger the build?

**Comment by nckturner** [comment]
This should be updated: https://github.com/aws/eks-charts/blob/gh-pages/index.yaml#L293
