### ISSUE TITLE
Support for K8s Priority Class

### ISSUE THREAD

**Issue by paliwalvimal** [aws/eks-charts#462]
**Is your feature request related to a problem?**
Support for Priority Class will make sure that mesh controller pods are always up and running before other ones like virtual nodes, service, etc are started

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
appmesh-controller and appmesh-gateway

**Describe the solution you'd like**
I would like to raise PR for the same where we either create a new priority class or accept name from the user in the same way as the service account

**Describe alternatives you've considered**
Maintaining chart on my own but it will be hard to keep in sync every time

**Comment by bryantbiggs** [comment]
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located
