### ISSUE TITLE
[aws-load-balancer-controller] Failed to pull image 

### ISSUE THREAD

**Issue by SrikanthBhandary** [aws/eks-charts#467]
AWS load balancer pod is not running, and an image pulling issue is occured.

- Create an AWS faraget EKS cluster.
- Make sure the pod execution policy exists.
- Install AWS load balancer controller through helm chart
- And verify the pods in the name space kube-system.

**Expected outcome**
Aws load balancer controller pod should run without any issues.

**Environment**

* Chart name: AWS LoadBalancer Controller
* Chart version: 2.1
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version? 1.18

**Additional Context**:

Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:2.0": rpc error: code = NotFound desc = failed to pull and unpack image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:2.0": failed to resolve reference "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:2.0": 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:2.0: not found

**Comment by ChrisRut** [comment]
Seems to be hardcoded to us-west-2 here: https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml#L8

**Comment by 1riggs** [comment]
I've run into a similar issue. I am deploying this controller in the US Gov West region. The error output is: 

```
Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon/aws-load-balancer-controller/manifests/v2.0.0: no basic auth credentials 
```

**Comment by M00nF1sh** [comment]
@1riggs 
You need to pass in `--set image.repository=013241004608.dkr.ecr.us-gov-west-1.amazonaws.com/amazon/aws-load-balancer-controller:v2.1.3`  when installing. we'll update our docs for reflect this.

You can find the full list of images for each region in our release page: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.1.3

**Comment by 1riggs** [comment]
@M00nF1sh Ah that makes sense! I had a feeling it was something along those lines but wasn't sure of the current repository. Thanks a lot!

**Comment by harsh297-aws** [comment]
helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
  --namespace kube-system \
  --set clusterName=<Cluster_Name>\
  --set region=<region>\
  --set vpcId=<vpc_id>\
  --set serviceAccount.create=false \
  --set image.repository=602401143452.dkr.ecr.<region>.amazonaws.com/amazon/aws-load-balancer-controller \
  --set serviceAccount.name=aws-load-balancer-controller

Please replace the with the cluster details. 
Remove the version Tag and re-ran it worked.

**Comment by RimashMohomed** [comment]
Had the same issue, where we have deployed in eu-west-1 region but it works in both us-east-1 and us-east-2 regions without a issue. 

For anyone find this in future use `--set image.repository` and` -set image.tag` to indicate the ECR repo and version wanted to install

Below worked for me, ECR repos are listed in release note

`helm upgrade --install aws-load-balancer-controller $repo_name/aws-load-balancer-controller \
    --version 1.2.5 \
    -n kube-system \
    --set clusterName=$cluster_name \
    --set serviceAccount.create=false \
    --set serviceAccount.name=$service_account_name
    --set region=$aws_region \
    --set image.repository=602401143452.dkr.ecr.$aws_region.amazonaws.com/amazon/aws-load-balancer-controller \
    --set image.tag=v2.2.3`

**Comment by lteixeira-dock** [comment]
Kubernetes version 1.21, eks eks.5 version. The same issue occurs as this version is enabled by default on the STS ""Regional"" Endpoint, not the STS ""Global"" Endpoint.

For solve this problem I changed the ECR for same region of EKS Cluster.

Link for reference: https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html

**Comment by kishorj** [comment]
@SrikanthBhandary, I'm closing the issue. If problem persists, please file the issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/

**Comment by kyleli666** [comment]
I met this issue first time today, after a long time never having problem with the image repo.
Why does this issue not happen when the first time install with helm and without pointing an image repo?
