### ISSUE TITLE
resources defined for init containers

### ISSUE THREAD

**Issue by paulfictioner** [aws/eks-charts#470]
**Is your feature request related to a problem?**
It would be nice to have resources for init container defined in values file. Gatekeeper that scans my k8s throws alerts regarding resources for init container that are not defined.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
Charts with init container:
appmesh-prometheus
appmesh-spire-agent
aws-vpc-cni

**Describe the solution you'd like**
I would like to have resources defined for init container

**Comment by jdn5126** [comment]
@paulfictioner if this is still an issue for you, can you open an issue on the VPC-CNI repo: https://github.com/aws/amazon-vpc-cni-k8s ? We can mark this as a good first issue for someone to add

**Comment by jdn5126** [comment]
Looks like this is the same request as [#738](https://github.com/aws/eks-charts/issues/738), and will also be addressed by https://github.com/aws/amazon-vpc-cni-k8s/pull/2137

**Comment by jdn5126** [comment]
Closing as this was fixed by https://github.com/aws/amazon-vpc-cni-k8s/pull/2205. This will ship in the VPC CNI chart for v1.13.0
