### ISSUE TITLE
Appmesh controller logs say - not authorized to perform: appmesh:CreateMesh on resource even though policy allows

### ISSUE THREAD

**Issue by jayeshnazre** [aws/eks-charts#478]
**Describe the bug**
I followed the steps outlined in [https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller](url)

**Steps to reproduce**
**step1:** 
helm repo add eks https://aws.github.io/eks-charts
kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
**step2:** 
kubectl create ns appmesh-system
export CLUSTER_NAME=myeksctlcluster1
export AWS_REGION=us-east-1
export AWS_ACCOUNT_ID=XXXXX
**step3:**
eksctl utils associate-iam-oidc-provider --region=$AWS_REGION \
    --cluster=$CLUSTER_NAME \
    --approve
**step4:**
	curl -o controller-iam-policy.json https://raw.githubusercontent.com/aws/aws-app-mesh-controller-for-k8s/master/config/iam/controller-iam-policy.json

aws iam create-policy \
    --policy-name AWSAppMeshK8sControllerIAMPolicy \
    --policy-document file://controller-iam-policy.json
	
eksctl create iamserviceaccount --cluster $CLUSTER_NAME \
    --namespace appmesh-system \
    --name appmesh-controller \
    --attach-policy-arn arn:aws:iam::XXXXX:policy/AWSAppMeshK8sControllerIAMPolicy  \
    --override-existing-serviceaccounts \
    --approve
**step5:** 

helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
	--set logLevel=debug \
    --set region=$AWS_REGION \
    --set serviceAccount.create=false \
    --set serviceAccount.name=appmesh-controller

**step6:**
Create the namespace and the Custom Resource Mesh

apiVersion: v1
kind: Namespace
metadata:
  name: myappmeshns
  labels:
    mesh: myappmesh1
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled

apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: myappmesh1
spec:
  namespaceSelector:
    matchLabels:
      mesh: myappmesh1

**Expected outcome**
The AWS App mesh should have been created by the AWS Appmesh controller

**Environment**
* Helm: v3
* eksctl: v0.40.0
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? yes (eks.4)

**Additional Context**:
**I get the error in CloudTrail:**
 "errorMessage": "User: arn:aws:sts::XXXXXX:assumed-role/eksctl-myeksctlcluster1-addon-iamserviceacco-Role1-QH0STJ0UJ3HQ/1616183430576110317 is not authorized to perform: appmesh:CreateMesh on resource: arn:aws:appmesh:us-east-1:XXXXXX:mesh/myappmesh1 with an explicit deny",

**The appmesh controller logs the following error:**
{"level":"error","ts":1616184519.9091122,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"mesh","request":"/myappmesh1","error":"AccessDeniedException: \n\tstatus code: 403, request id: e7c19b77-9839-428d-ace3-f5bfd35b2e2c","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}

**I checked the service  account has:** 
 annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXX:role/eksctl-myeksctlcluster1-addon-iamserviceacco-Role1-QH0STJ0UJ3HQ
This was auto created with the eksctl iamserviceaccount command

**I checked the appmesh controller pod for mounts, and it has all the correct mounts/env set:** 
      AWS_DEFAULT_REGION:           us-east-1
      AWS_REGION:                   us-east-1
      AWS_ROLE_ARN:                 arn:aws:iam::XXXX:role/eksctl-myeksctlcluster1-addon-iamserviceacco-Role1-QH0STJ0UJ3HQ
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from appmesh-controller-token-8s6gf (ro)

**Comment by jayeshnazre** [comment]
@kishorj or @M00nF1sh  - guys one more similar problem. Just following the steps outlined in [https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller](url) and this time I also checked that the IAM role ARN is mounted in the AppMesh controller pod but get the above errors, once again any pointers?

**Comment by jayeshnazre** [comment]
Folks just checking, I am following the exact same steps outlined in the official documentation and am getting the above error. Any pointers?

**Comment by achevuru** [comment]
@jayeshnazre  Are you running in to issues only with Mesh create? From the cloudtrail logs you provided above, there seems to an explicit deny in one of the policies. Can you check what is contributing to that?

**Comment by jayeshnazre** [comment]
@ achevuru  
Let me check.

**Comment by jayeshnazre** [comment]
@achevuru  
Thanks for asking me that question. One of my admins had put an explicit deny via a policy which I was not aware of. As soon as I ran the same in my own AWS account it worked thereby confirming what you asked me to check (explicit deny was the root cause). 
@achevuru  
I have opened another bug to ask about incomplete documentation pertaining to Envoy IAM policy
[https://github.com/aws/eks-charts/issues/477](url) 
I ran into that problem as I did not have the appmesh:StreamAggregatedResources permissions and was not sure where the policy needs to be applied so to make it work I applied to the IAM role for the node (which is not right). But I believe the policy needs to be applied to the envoy proxy that the VirtualGateway uses to access the K8s services. Can you help me with that? This issue is resolved, thanks for helping me.

**Comment by cgchinmay** [comment]
@jayeshnazre If you don't have any more questions for this issue, could you close it ?

**Comment by achevuru** [comment]
Resolving it as the permissions issue was due to an explicit deny policy.
