### ISSUE TITLE
Specify Requests and Limits by default for aws-load-balancer-controller instead of optional null value

### ISSUE THREAD

**Issue by GokuOnCloud** [aws/eks-charts#481]
**Is your feature request related to a problem?**
If the current "aws-load-balancer-controller" eks helm chart is deployed to target dataplane of Fargate worker node type then the least capacity-provisioned tuple will be chosen by Fargate which is .25 vCPU | 0.5 GB. [Out of this capacity, 256MB will be required Kubernetes components (kubelet, kube-proxy, and containerd) as EKS documentation.](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html#fargate-cpu-and-memory)

This leaves to very less amount of memory for controller pod to survive in-case of starvation. Although we provide optional parameter with null value by default for users to configure in [values.yaml](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml#L46) file , this is in contradiction with the official manifests provided in the [kubernetes-sigs /aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_1_3_full.yaml) where the values are predefined explicitly.

By following the same practice in this chart will help inline with resemblance of how pod behaves despite of installation procedure which users use to follow and by mentioning this values under the values.yaml as same as official manifests file will help the users to configure higher value incase if required in future versions.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
e.g. aws-load-balancer-controller

**Comment by kishorj** [comment]
@GokuOnCloud, I'm closign the issue, please file it in the upstream repo https://github.com/kubernetes-sigs/aws-load-balancer-controller/.
