### ISSUE TITLE
[appmesh-controller] Appmesh controller has no PodDisruptionBudget

### ISSUE THREAD

**Issue by dpp23** [aws/eks-charts#490]
**Describe the bug**
The appmeshcontroller charts allows for multiple replicas, but doesn't have an option to create a PodDisruptionBudget. Because of this the `aws-node-termination-handler` cannot properly drain nodes that run the `appmesh-controller`. This also causes issues as there is an interuption to the service if the nodes get terminated with the pods running on them as this blocks the deployment of any other pod in the cluster.

**Environment**

* Chart name: appmesh-controller
* Chart version: 1.2.2
* Kubernetes version: 1.18
* Using EKS (yes/no), if so version? yes. 1.18

**Comment by achevuru** [comment]
@dpp23 Sure, we can look in to it. If you are interested please consider raising a PR.

**Comment by cgchinmay** [comment]
Closing this Issue as we have a PR to add this change: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/470
