### ISSUE TITLE
aws-load-balancer-controller crds not auto installed with `apiVersion: v1` 

### ISSUE THREAD

**Issue by bhegazy** [aws/eks-charts#495]
**Describe the bug**

when installing the chart crds are not auto installed due to helm chart apiVersion being v1

**Steps to reproduce**

Install the chart without applying crds, chart will failed with 

```
{"level":"error","ts":1617587134.5566506,"logger":"setup","msg":"unable to create controller","controller":"TargetGroupBinding","error":"no matches for kind \"TargetGroupBinding\" in version \"elbv2.k8s.aws/v1beta1\""}
```

This has failed with argocd setup, to mitigate it, I had created another resource to installed crds.

**Expected outcome**
Chart installed successfully

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 1.1.6
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version? yes  1.19.6 | eks.2

**Additional Context**:

I understand that in  the readme instructions mentioned to manually apply the crd first before chart install, however I was wondering why not changing the helm chart `apiVersion` to v2 and let it auto installed, is there any issue or backward compatibility issue for changing it to v2 ?
more details: https://helm.sh/docs/topics/v2_v3_migration/#overview-of-helm-3-changes

**Comment by chaosaffe** [comment]
Per the [Helm docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) CRD's should be installed as part of the chart (preferred) _or_ via a separate chart.

**Comment by kishorj** [comment]
@bhegazy, helm install/upgrade installs the CRDs on a fresh install. What is your helm version?

**Comment by chaosaffe** [comment]
>This has failed with argocd setup, to mitigate it, I had created another resource to installed crds.

ArgoCD uses `helm template` with the `--include-crds` flag to generate the manifests, then uses it's own logic to submit them to the Kubernetes API server. Since it doesn't use the `install` or `update` logic of Helm the CRD's are not installed, regardless of the Helm version while the `chart.yaml` `apiVersion` is set to `v1`

Until #501 is merged this issue will occur with any tools or processes using `helm template` to create the manifests.

**Comment by bhegazy** [comment]
> @bhegazy, helm install/upgrade installs the CRDs on a fresh install. What is your helm version?

Yep as @chaosaffe mentioned Argo uses helm template that is why #501 is needed or else it will fail to install crds

**Comment by mthoretton** [comment]
I created a [crds chart](https://artifacthub.io/packages/helm/aws-load-balancer-controller-crds/aws-load-balancer-controller-crds) in the meantime. Unfortunately with terraform you cannot easily apply plain manifests as kubernetes_manifest resources is still in beta mode 😢

**Comment by kishorj** [comment]
we will move to helm v3 chart for the aws-load-balancer-controller. Closing this issue. If there are further concerns on this matter, feel free to create an issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller.
