### ISSUE TITLE
[aws-load-balancer-controller] Bundle servicemonitor for prometheus-operator integration

### ISSUE THREAD

**Issue by mikhailadvani** [aws/eks-charts#498]
**Is your feature request related to a problem?**
Though prometheus metrics are exposed by the controller pod, a servicemonitor needs to be deployed separately. Since this is a generic reusable component, it makes sense to bundle it in the helm chart itself.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-load-balancer-controller

**Describe the solution you'd like**
Have a service for the metrics port and optionally deploy the servicemonitor resource.

**Describe alternatives you've considered**
NA

**Comment by kishorj** [comment]
closing the issue, already fixed upstream.
