### ISSUE TITLE
EKS Kube-Bench Scheduler

### ISSUE THREAD

**Issue by ashutoshupadhyay** [aws/eks-charts#528]
**Is your feature request related to a problem?**
As a security consultant I would like to have a scheduled aquasec kube-bench execution to have a periodic review of benchmarks.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aquasec/kube-bench

**Describe the solution you'd like**
Execute kube-bench on an hourly and daily basis

**Describe alternatives you've considered**
Use ctrl-m scheduler

**Comment by ashutoshupadhyay** [comment]
I have a working helm chart to solve this problem. Please advise how could I contribute.

**Comment by bryantbiggs** [comment]
https://github.com/aws/eks-charts/pull/530#issuecomment-2371440401
