### ISSUE TITLE
[aws-node-termination-handler] patch-release is backwards incompatible

### ISSUE THREAD

**Issue by mhulscher** [aws/eks-charts#546]
**Describe the bug**
Upgrading helm-chart aws-node-termination-handler from 0.15.0 to 0.15.1 is impossible because of a breaking change.

```
Error: failed to replace object: RoleBinding.rbac.authorization.k8s.io "aws-node-termination-handler-psp" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"aws-node-termination-handler-psp"}: cannot change roleRef
```

**Steps to reproduce**
Upgrade aws-node-termination-handler from 0.15.0 to 0.15.1 with RBAC and PSP enabled.

**Expected outcome**
Upgrade should work.

**Environment**

* Chart name: **aws-node-termination-handler**
* Chart version: **0.15.0 -> 0.15.1**
* Kubernetes version: **1.19**
* Using EKS (yes/no), if so version? **v1.19.8-eks-96780e**

**Additional Context**:

N/A

**Comment by bwagner5** [comment]
Apologies for the inconvenience here. We do not have helm upgrade tests for NTH, so I think that would be a good addition to make sure this doesn't happen again.  Uninstalling and reinstalling the chart should work fine to upgrade.
