### ISSUE TITLE
ALB Controller TLS cert upgrade behavior is not documented explicitly

### ISSUE THREAD

**Issue by ceroloy** [aws/eks-charts#558]
**Is your feature request related to a problem?** 
Running helm diff across our alb controller chart even with same version produces a diff and it says the TLS certs will be updated.
At the moment we are upgrading our cluster's k8s versions and got confused by this diff combined with the `admissionregistration.k8s.io/v1beta1` deprecation/removal messages.

While searching for whether the commit updating from v1beta1 to v1 is included in our version of the chart, and thus causing the diff, I ended up finding #555 and learnt that the behavior is independent of the version changes, and in fact a default behavior given helper functions in the chart.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
AWS Load Balancer Controller chart.

**Describe the solution you'd like**
If the cert update behavior won't change any time soon, please explicitly document that TLS certs will be changed with every upgrade/install command and this diff is expected and can be ignored.

**Describe alternatives you've considered**
N/A

**Comment by kishorj** [comment]
@ceroloy, issue similar to https://github.com/aws/eks-charts/issues/562. We will provide an option to reuse the existing TLS certs on upgrade. I'm closing the issue.
