### ISSUE TITLE
aws-vpc-cni chart v1.1.8/app v1.9.0 not yet published

### ISSUE THREAD

**Issue by morganchristiansson** [aws/eks-charts#564]
**Steps to reproduce**

```
$ helm repo update
<snip>
$ helm search repo eks/aws-vpc-cni
NAME            CHART VERSION   APP VERSION     DESCRIPTION                     
eks/aws-vpc-cni 1.1.7           v1.8.0          A Helm chart for the AWS VPC CNI
```

**Expected outcome**

New aws-vpc-cni  chart v1.1.8 from PR #563 is not yet available.

**Environment**

* Chart name: aws-vpc-cni
* Chart version: 1.1.8
* Kubernetes version: 1.20
* Using EKS: yes

**Additional Context**:

Appears @eks-bot has not published changes to [the gh-pages branch](https://github.com/aws/eks-charts/tree/gh-pages)

Manifest https://aws.github.io/eks-charts/index.yaml downloaded by helm does not yet contain v1.1.8/v1.9.0

**Comment by morganchristiansson** [comment]
Maybe someone needs to create new release of eks-charts? Last push to gh-pages seems to have been triggered by release..

https://github.com/aws/eks-charts/releases

I'm eager to be able to try 1.9.0 release.

**Comment by stevehipwell** [comment]
@morganchristiansson a maintainer will need to tag the repo to release the charts.

**Comment by jayanthvn** [comment]
Sorry for the delay. We are working on the charts release. Should be out soon.

**Comment by morganchristiansson** [comment]
https://github.com/aws/eks-charts/releases/tag/v0.0.55
