### ISSUE TITLE
/* path error on latest Ingress with `networking.k8s.io/v1`

### ISSUE THREAD

**Issue by ns0092** [aws/eks-charts#569]
```{"level":"error","ts":1627597396.9217522,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"sample-ingress","namespace":"default","error":"ingress: default/sample-ingress: prefix path shouldn't contain wildcards: /*"```

Ingress does not treat `/` path as `/*`. However, everything works fine with path as `/*` but the controller has this above error ⬆️ 

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: v1.2.3
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? Yes, 1.20

**Additional Context**:
App Version: v2.2.1

**Comment by M00nF1sh** [comment]
@ns0092 
There is PathType associated with each path. For "Prefix" type, it shouldn't contain any wild cards.
You may use "ImplementationSpecific" path type if you want to specify the path per ALB's syntax.

see https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
and https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1772

**Comment by kishorj** [comment]
@ns0092, closing the issue. If you still have the problem, feel free to open an issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller.
