### ISSUE TITLE
Install aws-load-balancer-controller CRDs using Helm

### ISSUE THREAD

**Issue by IvanovOleg** [aws/eks-charts#594]
**Is your feature request related to a problem?**
I want to install aws-load-balancer-controller CRDs using terraform. It fails due to the "status" section in the yaml template. Second problem - CRDs are too big to define them using the kubernetest_manifest resource.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
e.g. aws-load-balancer-controller

**Describe the solution you'd like**
I want CRDs included in the template folder and their installation controlled by a specific parameter called "installCRDs" pr something in the values file (like it's usually done in the other opensource charts)

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by zen** [comment]
@IvanovOleg 
According to the docs here: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/ Helm 3 should automatically install crds in `crds` folder. A far as I can see, this is happening already

**Comment by kishorj** [comment]
@IvanovOleg, I'm closing the issue. If you have further concerns, feel free to open an issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/
