### ISSUE TITLE
use "helm upgrade" deploy appmesh-controller, namespace not expected but default

### ISSUE THREAD

**Issue by yanmin950122** [aws/eks-charts#602]
**Describe the bug**

I use CDK deploy eks and follow https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller to deploy appmesh using kubectl in local environment. 

I have created my namespace(kubectl create ns appmesh-system) and iamserviceaccount as bellow.

![image](https://user-images.githubusercontent.com/24740678/133396375-03e16322-281e-4b76-a881-3e6fe5489dee.png)

but when I deploy appmesh-controller use 

```
helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
    --set region=ap-northeast-1 \
    --set serviceAccount.create=false \
    --set serviceAccount.name=appmesh-controller
```
It doesn't work. the console show a workload named appmesh-controller but in default namespace, like this:

![image](https://user-images.githubusercontent.com/24740678/133397112-4d89ccc7-1810-4af3-a69e-203f631997de.png)

the workload condition show:  error looking up service account default/appmesh-controller: serviceaccount "appmesh-controller" not found.

![image](https://user-images.githubusercontent.com/24740678/133397283-183f83db-c22f-4db2-94af-3d5443212e39.png)

But I have explicitly specified the namespace. When I try the "helm upgrade" commend again. It report an error like this:

![image](https://user-images.githubusercontent.com/24740678/133397852-c1502ccb-fcca-4907-986a-07c5ec923459.png)

**Expected outcome**

Tell me how to fix it plz.

**Environment**

* Chart name: appmesh-controller
* Chart version: 
* Kubernetes version:1.19
* Using EKS (yes/no), if so version? yes,eks.6

**Additional Context**:

**Comment by cgchinmay** [comment]
Could you update your helm repo ? 
```
helm repo update
```

What chart version are you using for this appmesh-controller ?

**Comment by yanmin950122** [comment]
> Could you update your helm repo ?
> 
> ```
> helm repo update
> ```
> 
> What chart version are you using for this appmesh-controller ?

I have update the helm. The current version is :

![image](https://user-images.githubusercontent.com/24740678/133547877-59c51423-727b-4e74-b844-fb4ad2b3cf27.png)

But it doesn't seem to work.

the appmesh-controller version is 1.0

![image](https://user-images.githubusercontent.com/24740678/133547981-1c39e4d7-56a2-424c-afd5-19ad9b73f278.png)

Thanks for your reply.

**Comment by cgchinmay** [comment]
Could you delete the existing appmesh-controller deployment and execute the below steps. I tested out and was able to correctly deploy appmesh-controller. I do see that your helm upgrade is giving you an error. 
1. helm repo update
Sample output
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "aws-ebs-csi-driver" chart repository
...Successfully got an update from the "eks" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "eks-test" chart repository
```

2.  kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
sample output
```
customresourcedefinition.apiextensions.k8s.io/gatewayroutes.appmesh.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/meshes.appmesh.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/virtualgateways.appmesh.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/virtualnodes.appmesh.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/virtualrouters.appmesh.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/virtualservices.appmesh.k8s.aws created
```

3. kubectl create ns appmesh-system
output
```
namespace/appmesh-system created
```

4.
```
export CLUSTER_NAME=<cluster name>
export AWS_REGION=ap-northeast-1
export AWS_ACCOUNT_ID=<account_id>
```

5.
```
eksctl utils associate-iam-oidc-provider --region=$AWS_REGION \
    --cluster=$CLUSTER_NAME \
    --approve
```

7.
```
curl -o controller-iam-policy.json https://raw.githubusercontent.com/aws/aws-app-mesh-controller-for-k8s/master/config/iam/controller-iam-policy.json
```

8.
```
aws iam create-policy \
    --policy-name AWSAppMeshK8sControllerIAMPolicy \
    --policy-document file://controller-iam-policy.json
```

9.
```
eksctl create iamserviceaccount --cluster $CLUSTER_NAME \
    --namespace appmesh-system \
    --name appmesh-controller \
    --attach-policy-arn arn:aws:iam::$AWS_ACCOUNT_ID:policy/AWSAppMeshK8sControllerIAMPolicy  \
    --override-existing-serviceaccounts \
    --approve
```

10.
```
helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
    --set region=$AWS_REGION \
    --set serviceAccount.create=false \
    --set serviceAccount.name=appmesh-controller
```

```
kubectl get all -n appmesh-system
NAME                                      READY   STATUS    RESTARTS   AGE
pod/appmesh-controller-684dfd8cd5-ks8v4   1/1     Running   0          12s

NAME                                         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
service/appmesh-controller-webhook-service   ClusterIP   10.100.7.14   <none>        443/TCP   12s

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/appmesh-controller   1/1     1            1           13s

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/appmesh-controller-684dfd8cd5   1         1         1       13s
```

**Comment by yanmin950122** [comment]
> @yanmin950122
> Could you delete the existing appmesh-controller deployment and execute the below steps. I tested out and was able to correctly deploy appmesh-controller. I do see that your helm upgrade is giving you an error.
> 
> 1. helm repo update
>    Sample output
> 
> ```
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "aws-ebs-csi-driver" chart repository
> ...Successfully got an update from the "eks" chart repository
> ...Successfully got an update from the "jetstack" chart repository
> ...Successfully got an update from the "eks-test" chart repository
> ```
> 
> 1. kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"
>    sample output
> 
> ```
> customresourcedefinition.apiextensions.k8s.io/gatewayroutes.appmesh.k8s.aws created
> customresourcedefinition.apiextensions.k8s.io/meshes.appmesh.k8s.aws created
> customresourcedefinition.apiextensions.k8s.io/virtualgateways.appmesh.k8s.aws created
> customresourcedefinition.apiextensions.k8s.io/virtualnodes.appmesh.k8s.aws created
> customresourcedefinition.apiextensions.k8s.io/virtualrouters.appmesh.k8s.aws created
> customresourcedefinition.apiextensions.k8s.io/virtualservices.appmesh.k8s.aws created
> ```
> 
> 1. kubectl create ns appmesh-system
>    output
> 
> ```
> namespace/appmesh-system created
> ```
> 
> 
> ```
> export CLUSTER_NAME=<cluster name>
> export AWS_REGION=ap-northeast-1
> export AWS_ACCOUNT_ID=<account_id>
> ```
> 
> 
> ```
> eksctl utils associate-iam-oidc-provider --region=$AWS_REGION \
>     --cluster=$CLUSTER_NAME \
>     --approve
> ```
> 
> 
> ```
> curl -o controller-iam-policy.json https://raw.githubusercontent.com/aws/aws-app-mesh-controller-for-k8s/master/config/iam/controller-iam-policy.json
> ```
> 
> 
> ```
> aws iam create-policy \
>     --policy-name AWSAppMeshK8sControllerIAMPolicy \
>     --policy-document file://controller-iam-policy.json
> ```
> 
> 
> ```
> eksctl create iamserviceaccount --cluster $CLUSTER_NAME \
>     --namespace appmesh-system \
>     --name appmesh-controller \
>     --attach-policy-arn arn:aws:iam::$AWS_ACCOUNT_ID:policy/AWSAppMeshK8sControllerIAMPolicy  \
>     --override-existing-serviceaccounts \
>     --approve
> ```
> 
> 
> ```
> helm upgrade -i appmesh-controller eks/appmesh-controller \
>     --namespace appmesh-system \
>     --set region=$AWS_REGION \
>     --set serviceAccount.create=false \
>     --set serviceAccount.name=appmesh-controller
> ```
> 
> ```
> kubectl get all -n appmesh-system
> NAME                                      READY   STATUS    RESTARTS   AGE
> pod/appmesh-controller-684dfd8cd5-ks8v4   1/1     Running   0          12s
> 
> NAME                                         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
> service/appmesh-controller-webhook-service   ClusterIP   10.100.7.14   <none>        443/TCP   12s
> 
> NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/appmesh-controller   1/1     1            1           13s
> 
> NAME                                            DESIRED   CURRENT   READY   AGE
> replicaset.apps/appmesh-controller-684dfd8cd5   1         1         1       13s
> ```

I have sought help from aws support: The cause of the problem is that the helm command line doesn't transfer the parameter value of "--namespace" into the template of "appmesh-controller". I have open a issue in helm: https://github.com/helm/helm/issues/10147

**Comment by bacongobbler** [comment]
Your Helm version is...

![helm version v3.0.0-alpha.2](https://user-images.githubusercontent.com/24740678/133547877-59c51423-727b-4e74-b844-fb4ad2b3cf27.png)

I'd suggest upgrading to a supported release of Helm 3 before submitting issues. Helm 3.7.0 is the most recent release.

You are bound to run into a TON of issues. Because you're using a pre-alpha release of Helm 3 that was never meant to be used in a production setting.

**Comment by cgchinmay** [comment]
@bacongobbler thanks for commenting. @yanmin950122 Let me know if you have any more questions, else I will close this one.
