### ISSUE TITLE
AppMesh-Gateway with 2 GatewayRoutes - update needs >15min

### ISSUE THREAD

**Issue by RafalMaleska** [aws/eks-charts#605]
**Describe the bug**
I'm using AppMesh-Controller 1.4.0 and the AppMesh-Gateway 0.1.5 on EKS 1.20. With ACM for Certificates, CloudMap for ServiceDiscovery. 

Envoy is not routing for more than 30min after adding more than one GatewayRoute

**Steps to reproduce**

After adding the first GatewayRoute with hostname routing the routing is working immediately. 

Tested with: 

curl -vvvk https://a3b299560fe9445ad11acab217e94571-652139da2b8cd662.elb.eu-central-1.amazonaws.com -H "Host: mesh-ingress-test1.cnp.comp.test.com"

 When adding another GatewayRoute with hostname routing (to another VirtualService) and testing with: 
 
 curl -vvvk https://a3b299560fe9445ad11acab217e94571-652139da2b8cd662.elb.eu-central-1.amazonaws.com -H "Host: mesh-ingress-test2.cnp.comp.test.com"
 
 The curl is returning: 
 
 `
 * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.cnp.comp.test.com
*  start date: Apr 22 00:00:00 2021 GMT
*  expire date: May 21 23:59:59 2022 GMT
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: mesh-ingress-test2.cnp.comp.test.com
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 159
< content-type: text/plain
< date: Wed, 22 Sep 2021 08:54:11 GMT
< server: envoy
< x-envoy-upstream-service-time: 31
< 
* Connection #0 to host af1f8403e24fc43d1998e03c3dca4a63-9adb510e5dd39ac6.elb.eu-central-1.amazonaws.com left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: Secret is not supplied by SDS
`

After approx. 30min the routing is working as expected.

**Expected outcome**
I'm expecting the routing to work immediately after adding a GatewayRoute

**Environment**

* Chart name: appmesh-controller, appmesh-gateway
* Chart version: 1.4.0, 0.1.5
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? yes, 1.20

**Comment by cgchinmay** [comment]
@RafalMaleska are you using the latest envoy image ? 
The appmesh-gateway chart is using an older envoy version (1.15) in the Charts. We are currently have the latest (1.19) envoy released. Could you try updating the envoy image ?

**Comment by RafalMaleska** [comment]
@cgchinmay I'm facing this issue with "aws-appmesh-envoy:v1.18.3.0-prod". 

more interesting, the envoys need more time to start around evening times (16:00-19:00 CET). 

Will switching to 1.19 help?

**Comment by suniltheta** [comment]
Hi @RafalMaleska I would like to know more about your setup. Are you using mTLS between Gateway envoy & the backend virtual services?

I see there is a PR from you to introduce the initialDelaySeconds for liveness and readiness https://github.com/aws/eks-charts/pull/604

So to understand the problem, envoy is not ready to accept the traffic before ~70 seconds from the boot up. The Kube pod liveness will determine that the container is not healthy and do a restart on the envoy container? As you have also mentioned that envoy will end up in "crash-loop after a restart", is this due to envoy receiving the SIG_TERM (`[2021-09-21 16:11:58.628][1][warning][main] [source/server/server.cc:702] caught ENVOY_SIGTERM`) from the Kube pod?

I am yet to determine that your issue would be directly related to an existing issue on Envoy OSS https://github.com/envoyproxy/envoy/issues/17529 . There is ongoing work by the community to address this long due issue. However I am still not sure if the two are indeed related because as you mention you are using CloudMap for ServiceDiscovery (EDS) but the HC delay is affecting DNS ServiceDiscovery (LOGICAL_DNS).

**Comment by RafalMaleska** [comment]
using TLS with ACM (as full AWS managed mTLS is not really possible with K8S and ACM) and IRSA for IAM and CloudMap for ServiceDiscovery all on EKS. Currently with envoy 1.18

This issue is about the strange behavior of the IngressEnvoy when adding additional gatewayroutes. After adding the first one it works fine, after adding it's not possible to use the second route for aprox. 15-30min sometimes longer, a restart of the ingress pods dosen't help. Moreover the pods will get than in an endless restart cycle: 

https://awsappmesh.slack.com/archives/C0113RB44C9/p1632240885010800


I've added the pull request to increase time for initializing of the envoy, because the helm chart didn't define any livenessProbe and the default livenessProbe caused the pods to restart after liveness time if reached(envoy was not fully initialized). The endless restart loop was observed only with gatewayroutes in the cluster and after restarting a pod.


```
[2021-09-21 16:11:58.591][1][debug][http] [source/common/http/filter_manager.cc:779] [C5][S17975011370086432354] request end stream
[2021-09-21 16:11:58.591][1][debug][admin] [source/server/admin/admin_filter.cc:66] [C5][S17975011370086432354] request complete: path: /server_info
[2021-09-21 16:11:58.592][1][debug][http] [source/common/http/conn_manager_impl.cc:1469] [C5][S17975011370086432354] encoding headers via codec (end_stream=false):
':status', '200'
'content-type', 'application/json'
'cache-control', 'no-cache, max-age=0'
'x-content-type-options', 'nosniff'
'date', 'Tue, 21 Sep 2021 16:11:58 GMT'
'server', 'envoy'

[2021-09-21 16:11:58.593][1][debug][connection] [source/common/network/connection_impl.cc:633] [C5] remote close
[2021-09-21 16:11:58.593][1][debug][connection] [source/common/network/connection_impl.cc:243] [C5] closing socket: 0
[2021-09-21 16:11:58.593][1][debug][conn_handler] [source/server/active_tcp_listener.cc:76] [C5] adding to cleanup list
[2021-09-21 16:11:58.628][1][warning][main] [source/server/server.cc:702] caught ENVOY_SIGTERM
[2021-09-21 16:11:58.629][1][info][main] [source/server/server.cc:823] shutting down server instance
[2021-09-21 16:11:58.629][1][info][main] [source/server/server.cc:769] main dispatch loop exited
[2021-09-21 16:11:58.629][1][debug][main] [source/server/server.cc:209] flushing stats
[2021-09-21 16:11:58.629][1][debug][main] [source/server/server.cc:219] Envoy is not fully initialized, skipping histogram merge and flushing stats
[2021-09-21 16:11:58.629][1][debug][init] [source/common/init/watcher_impl.cc:31] ClusterImplBase destroyed
[2021-09-21 16:11:58.629][1][debug][init] [source/common/init/watcher_impl.cc:31] init manager Cluster cds_ingress_cnp-mesh_cnp-appmesh-gateway-idbf-iat-nncr4_appmesh-ingress_self_redirect_http_15001 destroyed
[2021-09-21 16:11:58.629][1][debug][init] [source/common/init/watcher_impl.cc:31] ClusterImplBase destroyed
```

**Comment by cgchinmay** [comment]
This Issue has been worked on and is tracked here: https://github.com/aws/aws-app-mesh-roadmap/issues/360.

**Comment by RafalMaleska** [comment]
@cgchinmay thanks! 

I was not sure which place is the right place to open the issues (chart repo or roadmap repo).

**Comment by cgchinmay** [comment]
@RafalMaleska I can tell you that issue has been worked on and you can redirect all your communication over here: aws/aws-app-mesh-roadmap#360 So Closing this one.
