### ISSUE TITLE
[aws-load-balancer-controller] Add support for deployment as DaemonSet option

### ISSUE THREAD

**Issue by runlevel5** [aws/eks-charts#618]
**Is your feature request related to a problem?**

Having the controller running on all nodes would greatly increase the availability

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**

* aws-load-balancer-controller

**Describe the solution you'd like**

A helm chart value to deploy the controller as DaemonSet or Deployment:

```
deployment:
  kind: [DaemonSet|Deployment]
```

**Describe alternatives you've considered**

N/A

**Comment by kishorj** [comment]
@runlevel5, closing the issue for now. If you have further concerns, feel free to create an issue in the upstream repo https://github.com/kubernetes-sigs/aws-load-balancer-controller/
