### ISSUE TITLE
ALB ingress resource in EKS - could not be patched: admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClass.networking.k8s.io

### ISSUE THREAD

**Issue by e-jjj** [aws/eks-charts#628]
When updating the api version to `apiVersion: networking.k8s.io/v1` in the ingress resource (alb-ingress-connect-proxy-internal). Replacing the annotation, `kubernetes.io/ingress.class: alb` with the below under spec, which is required in the updated api version,

```yaml
spec:
  ingressClassName:  alb
``` 

The ingress resource can not be updated and returns the following error,
```
error: ingresses.networking.k8s.io "alb-ingress-connect-proxy-internal" could not be patched: admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClass.networking.k8s.io "alb" not found

Expect to update the ingress resource 

* Chart name: aws-load-balancer-controller
* Chart version: aws-load-balancer-controller-1.3.2
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? Yes, 1.20

**Comment by e-jjj** [comment]
Thanks @kishorj that was it. I upgraded the helm chart with the `--set ingressClass=alb` parameter.

**Comment by kishorj** [comment]
@e-jjj, I'm closing the issue for now. If you encounter further problems, you can file an issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/
