### ISSUE TITLE
Helm Chart for the csi-secrets-store-provider-aws provider

### ISSUE THREAD

**Issue by pierluigilenoci** [aws/eks-charts#633]
**Is your feature request related to a problem?**

I wrote a chart to deploy csi-secrets-store-provider-aws provider and opened a PR on the project repo.
Ref: https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35

It has been lying ignored for months and so I wondered where I was wrong.

Should I do the PR for the above chart in this repo? 

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**

csi-secrets-store-provider-aws

**Describe the solution you'd like**

Propose a new chart

**Describe alternatives you've considered**

Find someone on AWS who can approve my chart in the other repo 
https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35

**Comment by pierluigilenoci** [comment]
@cgchinmay @shaileshgupta2k @achevuru

**Comment by pierluigilenoci** [comment]
@willtong1234 @yuriadams @LeandroFranciscato @parimaldeshmukh @StevenEmelander @joebaro @lasred @NissesSenap could you please take a look?

**Comment by bwagner5** [comment]
Most new charts published are being put into the main app repo and sync'd over, so you were correct to pursue that route. But let's put this one in eks-charts first and then we can look at moving the main copy to the app repo later with a sync process.

**Comment by pierluigilenoci** [comment]
@bwagner5 let me know if there is anything else I can do. 

Fast recap: 
* https://github.com/aws/eks-charts/issues/633 (this issue)
* https://github.com/aws/eks-charts/pull/651 (PR to merge the chart in this repo)
* https://github.com/aws/eks-charts/issues/354 (a related issue in this repo)
* https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/15 (an issue in the software repo)
* https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/35 (PR in the software repo)
* https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/55 (a related issue in the software repo)
* https://github.com/aws/secrets-store-csi-driver-provider-aws/pull/56 (related PR in the software repo)
* https://github.com/portefaix/portefaix-hub/pull/103 (related PR in another repo)

**Comment by pierluigilenoci** [comment]
The [PR](https://github.com/aws/eks-charts/pull/651) is merged so we can close this issue.
