### ISSUE TITLE
 The environment variable APPMESH_RESOURCE_ARN of the Envoy container does not exist.

### ISSUE THREAD

**Issue by esteban-eg-kim** [aws/eks-charts#640]
**Describe the bug**
A concise description of what the bug is.

https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy-config.html
The AWS User Guide explains that APPMESH_RESOURCE_ARN is required for envoy version 1.15 or higher.
However, when app mesh gateway is installed with helm, APPMESH_VIRTUAL_NODE_NAME variable is created instead of APPMESH_RESOURCE_ARN even though the envoy version is 1.19.

**Steps to reproduce**
1. Install App Mesh Gateway with Helm

**Expected outcome**
There is an APPMESH_RESOURCE_ARN environment variable. 

**Environment**

* Chart name: appmesh-gateway
* Chart version: 0.1.5
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version?  **YES** eks.3

**Additional Context**:

Pod information after creation from AWS Console.

Image
840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:**v1.19.1.0-prod** 

**Environment variables**
ENVOY_LOG_LEVEL=info
ENVOY_ADMIN_ACCESS_PORT=9901
ENVOY_ADMIN_ACCESS_LOG_FILE=/tmp/envoy_admin_access.log
**APPMESH_VIRTUAL_NODE_NAME**=mesh/test-mesh/virtualGateway/main-igw-appmesh-gateway_******
AWS_REGION=ap-northeast-2
APPMESH_PREVIEW=0
AWS_ROLE_ARN=arn:aws:iam::427026******:role/******-main-cluster-sa-virtual-gateway-proxy-auth-main-igw
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

**Comment by bryantbiggs** [comment]
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located
