### ISSUE TITLE
CNI plugin fail to reach the API Server

### ISSUE THREAD

**Issue by ErikLundJensen** [aws/eks-charts#660]
**Describe the bug**
"My Amazon VPC Container Network Interface (CNI) plugin fails to reach the API Server in Amazon Kubernetes Service (Amazon EKS)."
See also AWS documentation of the problem and work-a-round:
https://aws.amazon.com/premiumsupport/knowledge-center/eks-vpc-cni-plugin-api-server-failure/

The aws-vpc-cni chart should define the initContainer as stated in AWS solution.

**Implementation question**: Should the initContainer be set by default?

**Steps to reproduce**

Typical seen when scaling cluster's nodepool from 0 to x

**Expected outcome**
CNI should wait for Kubernetes API to become online before trying to setup network.

**Environment**

* Chart name: aws-vpc-cni
* Chart version: (1.1.10)
* Kubernetes version: 1.21.2
* EKS version: v1.21.2-eks-0389ca3

**Comment by jdn5126** [comment]
An issue like this belongs on https://github.com/aws/amazon-vpc-cni-k8s repo. Since this appears to not be a current issue, closing this here.
