### ISSUE TITLE
Update documentation to enable TLS version and cipher headers on ELB

### ISSUE THREAD

**Issue by phgeraldeli** [aws/eks-charts#668]
**Is your feature request related to a problem?**
I'm using aws-load-balancer-controller chart to create my ELB at work, and i searched on docs and didn't find any clues on how to enable "TLS version and cipher headers" on my values.yaml. 

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-load-balancer-controller

**Describe the solution you'd like**
Been able to set a variable on values.yaml that enable it on AWS.

**Comment by kishorj** [comment]
@phgeraldeli, please open the issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/
