### ISSUE TITLE
401 unauthorized while trying to pull aws-load-balancer-controller image

### ISSUE THREAD

**Issue by luke-plausin-kidsloop** [aws/eks-charts#703]
**Describe the bug**

I am trying to deploy the official `aws-load-balancer-controller` helm chart. I have not changed the default tag, which in my case is `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.0`.

The chart deployment fails with an image pull error.

I tried pulling the image both on my local machine and on the Kubernetes nodes. Image `v2.4.0` also fails with the same error.

**Steps to reproduce**

```bash

$ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.0
FATA[0000] failed to resolve reference "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.3.5": pulling from host 602401143452.dkr.ecr.us-west-2.amazonaws.com failed with status code [manifests v2.3.5]: 401 Unauthorized
```

**Expected outcome**
The image should pull correctly without any authorization errors.

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: 1.3.2 (also latest version)
* Kubernetes version: 1.21
* Using EKS (yes/no), if so version? yes - eks.4

**Comment by luke-plausin-kidsloop** [comment]
@jamiebuxxx  I used chart overrides to switch the chart repo to the one in dockerhub.

```
image:
  repository: amazon/aws-alb-ingress-controller
```

https://hub.docker.com/r/amazon/aws-alb-ingress-controller

**Comment by kishorj** [comment]
@luke-plausin-kidsloop, I'm closing the issue. If problem persists, please open the issue in the upstream GitHub repo https://github.com/kubernetes-sigs/aws-load-balancer-controller/
