### ISSUE TITLE
[aws-for-fluent-bit] Support K8s v1.22+ Roles API

### ISSUE THREAD

**Issue by matanbaruch** [aws/eks-charts#707]
**Describe the bug**
Support K8s v1.22+ Roles API
v1.22+ K8s version deleted the v1beta1 API

[RBAC resources
The Beta API version of ClusterRole, ClusterRoleBinding, Role, and RoleBinding is no longer served as of version 1.22. Migrate manifests and API clients to use the rbac.authorization.k8s.io/v1 API version.](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22#rbac-resources-v122)

**Expected outcome**
Change from v1beta1 to v1

From 
`apiVersion: rbac.authorization.k8s.io/v1beta1`
To
`apiVersion: rbac.authorization.k8s.io/v1`

* Chart name: aws-for-fluent-bit
* Chart version: latest
* Kubernetes version: v1.22
* Using EKS (yes/no), if so version? yes, v1.21

**Additional Context**:
Changes should take place in the following files
[aws-for-fluent-bit/templates/clusterrole.yaml](https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/templates/clusterrole.yaml)
[aws-for-fluent-bit/templates/clusterrolebinding.yaml](https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/templates/clusterrolebinding.yaml)

**Comment by uaccount-colind** [comment]
With the recent release of Kubernetes 1.22 on EKS, this has become a breaking issue for us. https://github.com/aws/eks-charts/pull/662 addresses this, any chance it can be merged asap? Thanks.

**Comment by jaypipes** [comment]
Latest Chart uses the v1 not v1beta API version. Closing this one out.
