### ISSUE TITLE
New charts are not being published

### ISSUE THREAD

**Issue by take-five** [aws/eks-charts#709]
**Describe the bug**
Chart `aws-node-termination-handler 0.18.0` is not available from Helm.

**Steps to reproduce**
```
$ helm repo add eks https://aws.github.io/eks-charts
$ helm search repo  aws-node-termination-handler
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
eks/aws-node-termination-handler	0.17.0       	1.15.0     	A Helm chart for the AWS Node Termination Handler.
```

**Expected outcome**
Expected chart version  0.18.0 to be available.

**Environment**

* Chart name: aws-node-termination-handler
* Chart version: 0.18.0
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? Yes, 1.20

**Additional Context**:
I noticed that CircleCI build is actually failing even though jobs are marked as successful (see [this job](https://app.circleci.com/pipelines/github/aws/eks-charts/1332/workflows/737fc4f5-3196-4501-8f3e-49b59619c349/jobs/3207), for example).

**Comment by archoversight** [comment]
https://github.com/aws/eks-charts/commit/56b199a358720b03bc5d30e006e3b1ae95112010

shows it is has now been published.
