### ISSUE TITLE
Deprecated default Certificate version in aws-loadbalancer-controller chart

### ISSUE THREAD

**Issue by LukeRobbo** [aws/eks-charts#718]
**Describe the bug**
aws-loadbalancer-controller provisions a certificate by default as a serving-cert.
The apiVersion it's configured with is now out of date as of https://github.com/cert-manager/cert-manager/releases/tag/v1.7.0

```
 854 ---
 855 apiVersion: cert-manager.io/v1alpha2
 856 kind: Certificate
 857 metadata:
```
Should configure the default apiVersion to be v1 now that v1alpha2 is out of support.

**Steps to reproduce**

**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Chart name:
* Chart version:
* Kubernetes version:
* Using EKS (yes/no), if so version?

**Additional Context**:

**Comment by kishorj** [comment]
@LukeRobbo, the recent chart checks for recent version of cert-manager via Capabilities and use the v1 version. How do you install the chart - do you use templates or some cd tools?

**Comment by kishorj** [comment]
@LukeRobbo, I'm closing the issue. If it is still unresolved, please report the issue in the upstream repo - https://github.com/kubernetes-sigs/aws-load-balancer-controller/
