### ISSUE TITLE
node-termination-handler servicemonitor has the wrong labels

### ISSUE THREAD

**Issue by James-Quigley** [aws/eks-charts#722]
**Describe the bug**
The selectors on the servicemonitor do not match the labels on the service. Namely `app.kubernetes.io/component: deployment`. Therefore metrics cannot be scraped because there is no matching target

**Steps to reproduce**

Deploy the helm chart in queue mode, and enable the servicemonitor

**Expected outcome**
The selectors on the servicemonitor should match what exists on the service

**Environment**

* Chart name: 
aws-node-termination-handler
* Chart version:
0.18.0
* Kubernetes version:
1.21
* Using EKS (yes/no), if so version?
Yes. 1.21

**Additional Context**:

**Comment by jaypipes** [comment]
@bwagner5 any chance you can take a look into this one?

**Comment by bwagner5** [comment]
@James-Quigley this was recently fixed and will be released in eks-charts soon: https://github.com/aws/aws-node-termination-handler/pull/604
