### ISSUE TITLE
Unable to upgrade chart version from 0.16.0 to 0.18.1

### ISSUE THREAD

**Issue by varsha-chahar** [aws/eks-charts#727]
Getting below error while upgrading from 0.16.0 to 0.18.1 with default values as:
awsNodeTerminationHandler:
      chartVersion: 0.18.0
      description: "Managed gracefully handling EC2 instance shutdown within Kubernetes"
      enabled: true
      installed: false
      timeout:                                                         
      values:
        image:
          repository: "{{ .registry }}/ecr-public/aws-ec2/aws-node-termination-handler"
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 32Mi
      wait: false       

ERROR:
STDERR:
  W0410 23:26:26.705499   97382 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W0410 23:26:26.735505   97382 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W0410 23:26:26.779675   97382 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  Error: UPGRADE FAILED: cannot patch "aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "aws-node-termination-handler" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"daemonset", "app.kubernetes.io/instance":"aws-node-termination-handler", "app.kubernetes.io/name":"aws-node-termination-handler", "kubernetes.io/os":"linux"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by joebowbeer** [comment]
Please add `aws-node-termination-handler` to the title
