### ISSUE TITLE
working aws-for-fluent-bit not released

### ISSUE THREAD

**Issue by matti** [aws/eks-charts#734]
curl https://aws.github.io/eks-charts/index.yaml | grep https://aws.github.io/eks-charts/aws-for-fluent-bit

only shows `0.1.14` as latest, but https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/Chart.yaml#L4 shows that `0.16.1` is the latest and 0.1.14 is broken

🥇

**Comment by joebowbeer** [comment]
Please close. Fixed by #382
