### ISSUE TITLE
security groups and health check not being updated.

### ISSUE THREAD

**Issue by sn-asownie** [aws/eks-charts#740]
**Describe the bug**
the security groups for the nodes aren't being updated, and I'm not seeing any warns or errors in the logs

**Steps to reproduce**
im using version 1.2.7 of https://aws.github.io/eks-charts aws-load-balancer-controller
move from 17.x to 18.x of of the terraform provider for aws (terraform-aws-modules/eks/aws)

* Chart name: aws-load-balancer-controller
* Chart version: 1.2.7
* Kubernetes version: 1.2.1
* Using EKS (yes/no), if so version? yes, 18.20

**Comment by kishorj** [comment]
@sn-asownie, could you open the issue in the upstream repo https://github.com/kubernetes-sigs/aws-load-balancer-controller instead?

**Comment by sn-asownie** [comment]
opened
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2619

**Comment by kishorj** [comment]
we will use the upstream issue to track this, closing
