### ISSUE TITLE
TargetGroupBinding for another VPC

### ISSUE THREAD

**Issue by abatilo** [aws/eks-charts#745]
Very similar to https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1569

Currently, I am in a transition phase where we have a VPC with an ALB that runs an application. I want to run the application inside my EKS cluster that's in a different VPC. So I'm trying to create a `TargetGroupBinding` with the target group ARN for a target group that I created in the legacy VPC.

The solution in the above linked issue works if you have an instance of the aws-lb-controller running with `vpc-id` set to the legacy VPC. I have load balancers that already exist in my current EKS cluster, so I can't change the `vpc-id` of that instance. At the same time, it doesn't appear to be possible to install two copies of the LB controller so that I can set the VPC ID of the second instance, so that I can get the benefits of the `AvailabilityZone` = `all`.

So for now I have no way to update the `AvailabilityZone` for the targets since the only way that gets set is whether or not the pod IP address is NOT found in the CIDR for the vpc configured with the controller.

**Comment by kishorj** [comment]
closing the issue since we are already tracking it upstream
