### ISSUE TITLE
csi-secrets-store-provider-aws does not contain the secrets-store-csi-driver 

### ISSUE THREAD

**Issue by NamelessHH** [aws/eks-charts#748]
**Describe the bug**
The [documentation on the csi-secrets-store-provider-aws](https://github.com/aws/eks-charts/tree/master/stable/csi-secrets-store-provider-aws) clearly states `This chart installs the [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) and the AWS Secrets Manager and Config Provider for Secret Store CSI Driver`  but when you install only this chart the 
secrets-store-csi-driver is not installed only the aws provider

**Steps to reproduce**
install the csi-secrets-store-provider-aws helm chart

**Expected outcome**
It would be expected to weork out of the box including installing the secrets-store-csi-driver as stated in the documentation

**Environment**

* Chart name: csi-secrets-store-provider-aws
* Chart version: 0.0.2
* Kubernetes version: 1.19
* Using EKS (yes/no), if so version?
yes 1.19
**Additional Context**:
I think its fine to simply state in the documentation that this doesn't in fact install the base secrets-store-csi-driver just so no one has the expectation that it does.

**Comment by dza89** [comment]
Set:
secrets-store-csi-driver.install: to true

as defined in values.yaml

/close
