### ISSUE TITLE
[appmesh-controller] appVersion regression

### ISSUE THREAD

**Issue by gitfool** [aws/eks-charts#755]
**Describe the bug**
Unless I'm missing something, it looks like the appVersion was regressed from `v1.4.3` to `v1.4.2`. See https://github.com/aws/eks-charts/commit/70764493b75d67ef62b1ab41dd2b85eb57a6af9f#r73439840.

... and `v1.4.3` is needed for kubernetes 1.22 compatibility. See https://github.com/aws/aws-app-mesh-controller-for-k8s/releases.

**Environment**

* Chart name: `appmesh-controller`
* Chart version: `1.4.8`
* Kubernetes version: `1.22`
* Using EKS (yes/no), if so version? `1.22`

**Comment by jeremymill** [comment]
Closing this as this is fixed in the current controller version (1.5.0)
