### ISSUE TITLE
Support of Pod Topology Spread Constraints to aws-load-balancer-controller

### ISSUE THREAD

**Issue by msolimans** [aws/eks-charts#770]
**Is your feature request related to a problem?**
Support of Pod Topology Spread Constraints. 
More info https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
e.g. aws-load-balancer-controller

**Describe the solution you'd like**
Add support of  Pod Topology Spread Constraints to Ingress controller deployment. 

**Describe alternatives you've considered**
We are currently using AntiAffinity term but it doesn't have even distribution

**Comment by kishorj** [comment]
@msolimans, please open the issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller/

**Comment by kishorj** [comment]
EDIT: it is already supported upstream: https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/2575, we will include the changes in the next charts release.
