### ISSUE TITLE
Helm3 support for CRD under crd/ directory 

### ISSUE THREAD

**Issue by ramachittala** [aws/eks-charts#780]
As per this documentation one manual step is mentioned for crds installation. 
In helm3 crds will be installed under crd/ folder. 

https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller#upgrading-from--aws-load-balancer-controller-v213-and-earlier

**Comment by bdols** [comment]
agree, the documentation could mention that fresh helm 3 installs do not need to install the CRDs with `kubectl apply` beforehand, but chart upgrades will need to have special handling if the CRDs change.

**Comment by kishorj** [comment]
@ramachittala, chart install doesn't require CRD installation. Helm doesn't install/update CRDs for upgrade command.

**Comment by kishorj** [comment]
@ramachittala, recent live doc installation guide does mention the CRD step is not required for helm install commands. I'm closing this issue. If you have further concerns, please raise the issue in the upstream repo https://github.com/kubernetes-sigs/aws-load-balancer-controller
