### ISSUE TITLE
[aws-load-balancer-controller] Add option to make alb ingress class default

### ISSUE THREAD

**Issue by EqbalS** [aws/eks-charts#784]
**Is your feature request related to a problem?**
As mentioned in [kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class) you can make an IngressClass resource your default ingress class by settings the `ingressclass.kubernetes.io/is-default-class` annotation to `true` in the IngressClass resource. this is not supported in the `alb` ingress class created by this helm chart.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-load-balancer-controller

**Describe the solution you'd like**
2 approaches exist in my opinion:
- Adding the option to make the created ingress class the default ingress class (by adding the annotation)
- Adding the option to set custom annotations for the created ingress class

**Comment by kishorj** [comment]
We are already tracking it upstream https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2738, I'm closing the issue.
