### ISSUE TITLE
[appmesh-controller] - Append cluster name to mesh objects to avoid name collisions in multi-cluster setups

### ISSUE THREAD

**Issue by karrth** [aws/eks-charts#785]
**Is your feature request related to a problem?**
We're currently working on migrating applications to a new EKS cluster, and would like to stand up apps side-by-side in the same mesh to facilitate a smooth transfer.  Unfortunately, since the apps are deployed into the same namespace on each cluster, objects like the `VirtualNode`, `VirtualService`, etc, all collide in the mesh

While our situation is short lived (migration), I can see a use case for this where one wants multiple clusters to be hooked into the same mesh (ie, duplicate clusters in different regions for hot-failover), with consistent namespaces between them.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
appmesh-controller

**Describe the solution you'd like**
Append the cluster name to AppMesh created objects:
* `VirtualGateway`
* `VirtualService`
* `VirtualRouters`
* `VirtualNodes`

**Describe alternatives you've considered**
A current alternative is to have different namespaces per cluster.  The logical answer is to have a namespace named by the cluster name, but this feels and looks awkward, and makes it harder to stand up duplicate clusters in multiple regions from the same git repo without some gymnastics

**Comment by bryantbiggs** [comment]
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located
