### ISSUE TITLE
AWS Load Balancer Controller WAFV2 Disabale issue

### ISSUE THREAD

**Issue by kadamd-acc** [aws/eks-charts#786]
**Describe the bug**
we have configured aws load balancer controller using helm using terraform as IAC,  after deploying ingress services for ALB we are getting below error.
"Failed deploy model due to RequestError: send request failed caused by: Post “https://wafv2.eu-west-2.amazonaws.com/”: dial tcp 52.94.53.163:443: i/o timeout”
**Steps to reproduce**
 as per recommendation, for resolving this we have updated the helm resource with the below code where we set waf and shield as false, 

`resource "helm_release" "alb_controller" {

  name       = "aws-load-balancer-controller"
  repository = local.alb_controller_helm_repo
  chart      = local.alb_controller_chart_name
  version    = local.alb_controller_chart_version
  namespace  = var.k8s_namespace
  create_namespace = false
  atomic     = true
  timeout    = 900
  cleanup_on_fail = true

  set {
      name = "clusterName"
      value = var.k8s_cluster_name
      type = "string"
  }
  set {
      name = "serviceAccount.create"
      value = "false"
      type = "auto"
  }
  set {
      name = "serviceAccount.name"
      value = kubernetes_service_account.this.metadata[0].name
      type = "string"
  }
  set {
      name = "region"
      value = local.aws_region_name
      type = "string"
  }
  set {
      name = "vpcId"
      value = local.aws_vpc_id
      type = "string"
  }
  set {
      name =  "hostNetwork"
      value =   var.enable_host_networking
      type = "auto"
  }
  set {
      name = "enableWaf"
      value = "false"
  }
  set {
      name = "enableWaf2"
      value = "false"
  }
  set {
      name = "enableShield"
      value = "false"
  }
`
However, still we are getting "Failed deploy model due to RequestError: send request failed caused by: Post “https://wafv2.eu-west-2.amazonaws.com/”: dial tcp 52.94.53.163:443: i/o timeout” with ingress service.

**Expected outcome**
We expected we should not get such an error if we have set false for the waf and shield.

**Environment**
Dev

* Chart name: AWS Load Balancer Controller
* Chart version: v2.4.2
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? yes ,Version 1.22

**Additional Context**:

**Comment by kishorj** [comment]
@kadamd-acc, you have a typo in the value name. It should be `enableWafv2` instead of `enableWaf2`

**Comment by kishorj** [comment]
@kadamd-acc, I'm closing the issue since it is due to typo. If problem persists, please file it in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller
