### ISSUE TITLE
aws-load-balancer-controller - support feature-gates

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [aws/eks-charts#809]
**Is your feature request related to a problem?**
I want to enable feature SubnetsClusterTagCheck
using https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/deploy/configurations.md#feature-gates

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-load-balancer-controller

**Describe the solution you'd like**
extend arguments to support feature-gates

**Comment by kishorj** [comment]
@piotrwielgolaski-tomtom, please open the issue in the upstream repo https://github.com/kubernetes-sigs/aws-load-balancer-controller/

**Comment by kishorj** [comment]
Closing in favor of the upstream issue https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2775
