### ISSUE TITLE
aws-for-fluent-bit - remove PodSecurityPolicy

### ISSUE THREAD

**Issue by joebowbeer** [aws/eks-charts#810]
**Is your feature request related to a problem?**
There is no option to disable creation of [PodSecurityPolicy](https://kubernetes.io/docs/concepts/security/pod-security-policy/) (psp), which was deprecated in k8s 1.21 and will be removed in k8s 1.25

Relates to #476 

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-for-fluent-bit

**Describe the solution you'd like**
Add `podSecurityPolicy.create` with default value of `false`. 

See https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml#L35

**Describe alternatives you've considered**
* kustomize
* https://fluent.github.io/helm-charts

**Comment by yakir-shriker** [comment]
+1

**Comment by yacov-nagose** [comment]
+1

**Comment by joebowbeer** [comment]
Fixed by #888
