### ISSUE TITLE
Error: YAML parse error on aws-for-fluent-bit/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 29: could not find expected ':'

### ISSUE THREAD

**Issue by Viswajenny** [aws/eks-charts#818]
I'm referring this repository Helm chart's in my Terraform code. Earlier this is working as expected. But I'm facing issues from today. Thinking the y-days commits may be the cause. could you please help me with this ?
Error:
Error: YAML parse error on aws-for-fluent-bit/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 29: could not find expected ':'
with module.root_infrastructure.module.eks_observability.helm_release.aws_fluent_bit
on ../../modules/eks/observability/aws_fluent_logs_deployment.tf line 3, in resource "helm_release" "aws_fluent_bit":
resource "helm_release" "aws_fluent_bit" {
![image](https://user-images.githubusercontent.com/108377874/189030658-c756af44-03d2-4aef-9fb6-336b1a916bb4.png)

**Comment by q-harrybudd** [comment]
Here's the fix, I don't have the appropriate permissions to raise a PR

```
diff --git a/stable/aws-for-fluent-bit/templates/daemonset.yaml b/stable/aws-for-fluent-bit/templates/daemonset.yaml
index 0bb32b8..3803b4f 100755
--- a/stable/aws-for-fluent-bit/templates/daemonset.yaml
+++ b/stable/aws-for-fluent-bit/templates/daemonset.yaml
@@ -32,9 +32,9 @@ spec:
       {{- if .Values.hostNetwork }}
       hostNetwork: {{ .Values.hostNetwork }}
       {{- end }}
-      { { - if .Values.dnsPolicy } }
+      {{- if .Values.dnsPolicy }}
       dnsPolicy: {{ .Values.dnsPolicy }}
-      { { - end } }
+      {{- end }}
       containers:
         - name: {{ .Chart.Name }}
           imagePullPolicy: {{ .Values.image.pullPolicy }}

```

**Comment by SizZiKe** [comment]
this is breaking. Not sure how CI/reviews managed to allow a syntax error within a bugfix.

**Comment by jeremymill** [comment]
Reached out to fluent-bit team, looks like this was picked up in the charts release because it was already approved and merged.

**Comment by PettitWesley** [comment]
Test the latest patch from @matthewfala  and it works. We will release it shortly

**Comment by a0s** [comment]
Any news here?

**Comment by PettitWesley** [comment]
This was fixed here and released a year ago: https://github.com/aws/eks-charts/pull/819
