### ISSUE TITLE
aws-load-balancer-controller: support private-ipv4-addresses/eip-allocations

### ISSUE THREAD

**Issue by richardjharris** [aws/eks-charts#828]
**Is your feature request related to a problem?**
I would like to configure our gitlab instance to have static external IPs for firewall reasons. This appears possible upstream via https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#private-ipv4-addresses

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
e.g. aws-load-balancer-controller

**Describe the solution you'd like**
Add configuration for these values

**Describe alternatives you've considered**
If there is a way to set this value without needing the Helm chart to be updated, that is also fine. I don't know how to do that.

Thanks!

**Comment by kishorj** [comment]
@richardjharris, you can already specify the private ipv4 addresses vi the `service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses` annotation on your service. You need to:
- install the most recent chart
- meet the pre-reqs, for example NLB is internal, IP addresses are from the LB subnet range etc. Please refer to the live docs you mentioned for further details.

You need chart version 1.2.0 or later for this feature.
