### ISSUE TITLE
AWS EKS Fargate aws-load-balancer-controller endless pending state pod

### ISSUE THREAD

**Issue by iuyt9003** [aws/eks-charts#832]
**Describe the bug**
I tried to configure AWS EKS Fargate aws-load-balancer endless pending state.
and it's stuck in an endless pending state.

**Steps to reproduce**
This code: 
```
const clusterAdmin = new Role(this, 'eksClusterMasterRole', {
        roleName: `eksClusterMasterRole-${envName}`,
        assumedBy: new AccountRootPrincipal(),
    });

this.cluster = new eks.FargateCluster(this, 'nameEks', {
  version: eks.KubernetesVersion.V1_21,
  vpc: vpc,
  clusterName: `name-${envName}`,
  endpointAccess: eks.EndpointAccess.PUBLIC,
  mastersRole: clusterAdmin,
});

const albServiceAccount = this.cluster.addServiceAccount('aws-load-balancer-controller', {
  name: `aws-load-balancer-controller-${envName}`,
  namespace: 'kube-system',
});

const policyJson = albIamPolicy.Statement.forEach(statement => {
  albServiceAccount.addToPrincipalPolicy(PolicyStatement.fromJson(statement))
})

this.cluster.addHelmChart('aws-load-balancer-controller-helm-chart', {
  chart: 'aws-load-balancer-controller',
  repository: 'https://aws.github.io/eks-charts',
  namespace: 'kube-system',
  release: 'aws-load-balancer-controller',
  version: '1.4.5', // mapping to v2.4.4
  wait: true,
  timeout: cdk.Duration.minutes(15),
  values: {
    clusterName: this.cluster.clusterName,
    region: 'us-east-1',
    vpc: vpc.vpcId,
    serviceAccount: {
      create: false,
      name: `aws-load-balancer-controller-${envName}`,
    },
  },
});

```
**Expected outcome**
![image](https://user-images.githubusercontent.com/23431551/195960458-7a091538-4337-491c-9127-22f10203d71a.png)
That it won't be stuck in an endless pending state.

**Environment**
Kubernetes version v1.21.14
chart version: 1.4.5

* Chart name: aws-load-balancer-controller
* Chart version: 1.4.5
* Kubernetes version: 1.21.14
* Using EKS (yes/no), if so version? using CDK

**Additional Context**:
Thanks! I couldn't figure it out. from what I have seen it was should work.

**Comment by kishorj** [comment]
@iuyt9003, please open the issue in the upstream repository https://github.com/kubernetes-sigs/aws-load-balancer-controller instead.
