### ISSUE TITLE
Is the aws-vpc-cni chart recommended over the EKS addon?

### ISSUE THREAD

**Issue by trallnag** [aws/eks-charts#839]
I have noticed that AWS provides the VPC CNI in two ways.

1. Helm chart `aws-vpc-cni` within this repository.
2. EKS add-on "Amazon VPC CNI plugin" [here](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html).

Is one recommended over the other?

**Comment by trallnag** [comment]
Got an answer from AWS Premium Support.

> [...] As per the EKS Best practices guide [1], it is mentioned that "We highly recommend that you deploy clusters with managed add-ons including VPC CNI." So you can go ahead with using the managed add-on in your cluster. [...]

**Comment by jdn5126** [comment]
@trallnag yeah, managed add-ons are always recommended

**Comment by trallnag** [comment]
ok, thanks for the confirmation
