### ISSUE TITLE
appmesh-controller does not account for system architecture

### ISSUE THREAD

**Issue by jaydeland** [aws/eks-charts#857]
**Describe the bug**
The image tag always pulls the x86 docker container. This means it will not start on an arm64 node group.

**Steps to reproduce**
Using EKS Blueprints target a deployment to an arm64 node group.

**Expected outcome**
Should automatically choose the correct architecture

**Environment**

* Chart name: appmesh-controller
* Chart version: 1.9.0
* Kubernetes version: 1.23
* Using EKS (yes/no), if so version?
yes - 1.23

**Additional Context**:
Workaround is to update the tag parameter in the values.yaml file

**Comment by bendu** [comment]
https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/668

**Comment by bryantbiggs** [comment]
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located
