### ISSUE TITLE
ensure changed charts have updated chart version before release

### ISSUE THREAD

**Issue by jaypipes** [aws/eks-charts#88]
The release (to Helm repo) process for the eks-charts source repository is automated in a CircleCI job:

https://github.com/aws/eks-charts/blob/1e9ef68e9848dacc560996a04c7db16494e85f58/.circleci/config.yml#L53-L70

However, we do not currently ensure that when a Chart is updated in a Git commit since the last git tag on the source repository (i.e. the last release) that the Chart's `version` field is also updated.

We should ensure the `Chart.version` has changed for all charts that have been modified, otherwise we will have the same published Helm Chart version point to different configurations.

**Comment by bwagner5** [comment]
this issue can be closed I believe.
