### ISSUE TITLE
aws-calico: Add cpu/memory limits

### ISSUE THREAD

**Issue by enver** [aws/eks-charts#89]
It would be good to have the ability to specify cpu/memory requests/limits via values file. I'd be happy to provide PR if issue is accepted.

**Comment by jaypipes** [comment]
Agreed, @enver! Please feel free to push a PR that adds this functionality to the `aws-calico` chart. Please feel free to copy the approach used in the other charts for this:

https://github.com/aws/eks-charts/blob/master/stable/aws-node-termination-handler/values.yaml#L18-L24

including adding documentation for the value parameters to the readme!

Thanks very much! :)
-jay
