### ISSUE TITLE
Installing the TargetGroupBinding CRDs using the GitHub URL does not work

### ISSUE THREAD

**Issue by gergo-papp** [aws/eks-charts#939]
**Describe the bug**
According to the documentation [here](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/#summary), I'm supposed to install TargetGroupBinding CRDs before upgrading `aws-load-balancer-controller` using helm. This has worked perfectly fine over the years and we have multiple successful deployments from our CI pipeline.

Installing CDRs started failing recently.

**Steps to reproduce**

These are the commands that we have been running and they used to be successful:
```sh
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
helm repo add eks https://aws.github.io/eks-charts/ --force-update

template=$(envsubst < "k8s/aws-load-balancer-controller.values.yaml")
echo "$template" | helm upgrade aws-load-balancer-controller eks/aws-load-balancer-controller --version 1.2.0 --install --namespace kube-system -f -
```

I get the following errors since 27 April 2023:
```
error: failed to run '/usr/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/aws-load-balancer-controller master': remote: Not Found
fatal: repository 'https://github.com/aws/eks-charts/stable/aws-load-balancer-controller/' not found
```

If I navigate to [github.com/aws/eks-charts/stable/aws-load-balancer-controller](https://github.com/aws/eks-charts/stable/aws-load-balancer-controller) in a browser I also get a 404 error.

**Expected outcome**
I should be able to successfully apply the Kubernetes templates using `kubectl apply -k`. This used to work but now it fails with 

**Environment**

* Chart name: aws-load-balancer-controller
* Chart version: all versions
* Kubernetes version: 1.21.0
* Using EKS (yes/no), if so version? yes, 1.21.0

**Additional Context**:
GitHub recently changed their navigation (mostly affecting how the UI is rendered). It's possible that this messed up some of the save GitHub-related URLs.

**Comment by gergo-papp** [comment]
https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller/crds seems to be a correct URL

**Comment by johand-garcia** [comment]
I started to get the same error since April 19th 2023 in our CI/CD pipeline. As I already had the CRDs installed in my cluster I've omitted the TargetGroupBinding CRDs installation step but for new installations that's a problem.

Something weird is that if I run the command locally it works properly.

**Comment by yixuandang** [comment]
same issue here:
╰─ kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
error: failed to run '/usr/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/aws-load-balancer-controller master': remote: Not Found
fatal: repository 'https://github.com/aws/eks-charts/stable/aws-load-balancer-controller/' not found
: exit status 128

Any recommendations so far?

**Comment by antongo-papaya** [comment]
just change `//` to `/` in the link:
`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"` - > 
`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"`

**Comment by bryantbiggs** [comment]
what @antongo-papaya shared is correct - the README documentation has been updated to correct this
