### ISSUE TITLE
[aws-calico] crds/kustomization.yaml adding it to helmignore

### ISSUE THREAD

**Issue by jaekim09** [aws/eks-charts#94]
error msg: 
failed to upgrade chart for release [calico]: failed to install CRD crds/kustomization.yaml: unable to recognize "": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"

fluxcd helm-operator can't process the kustomization.yaml file. After adding skipCRDs in helm-operator seems to process ok. 
Looking at[ this commit ](https://github.com/aws/eks-charts/commit/b727affcb575f5a270b2e0099662b89daf3ac553#diff-9c9acd37bca006cc4df74780af311285) can aws calico do same?

**Comment by itsSaad** [comment]
Im also bitten by this. :(

**Comment by mbarrien** [comment]
Fixed in #102

**Comment by gsf** [comment]
Thanks! I think we can close this now. Looking forward to 0.2.1 in the chart repo.

**Comment by iuriaranda** [comment]
Any idea when 0.2.1 is going to be released on the chart repo? We've also stumbled upon this issue

**Comment by jaypipes** [comment]
Just cut the release: https://github.com/aws/eks-charts/releases/tag/v0.0.17
