### ISSUE TITLE
[aws-for-fluent-bit] no health checks to restart pod when not healthy

### ISSUE THREAD

**Issue by razorsk8jz** [aws/eks-charts#946]
**Describe the bug**
We ran into an issue where aws-for-fluent-bit stopped sending logs to cloudwatch - per fluent-bit's documentation there is a health check endpoint at /api/v1/health. We should have health checks to monitor this endpoint to ensure fluent-bit is healthy and restart the pod if it is not healthy

**Steps to reproduce**
I am not able to reproduce the issue in fluent-bit as it happened randomly after 47 days however there is no health checks that are configurable for aws-for-fluent-bit

**Expected outcome**
We should be able to turn on health checks 

**Environment**

* Chart name: aws-for-fluent-bit
* Chart version: 0.1.24
* Kubernetes version: 1.25.4
* Using EKS (yes/no), if so version?
no

**Additional Context**:

**Comment by razorsk8jz** [comment]
This was fixed by https://github.com/aws/eks-charts/pull/947

**Comment by jatinmehrotra** [comment]
The fix to this PR has  makes pod restart and ultimately CrashLoopBackOff

https://github.com/aws/eks-charts/issues/995
https://github.com/aws/eks-charts/issues/983
