### ISSUE TITLE
Issue with Enable X-Ray tracing for the App Mesh data plane section in manual

### ISSUE THREAD

**Issue by petrokashlikov** [aws/eks-charts#98]
Hi, there seems to be issue with step to Enable X-Ray tracing for the App Mesh data plane.

When you run this command, it actually takes default mesh name value "global" from Values.yaml and overwrites mesh name that you set during admission controller deployment. This basically breaks up mesh connectivity and is kind of unexpected, because you think you are just enabling 
additional component and not touching mesh name at this point. 

```
helm upgrade -i appmesh-inject eks/appmesh-inject \
--namespace appmesh-system \
--set tracing.enabled=true \
--set tracing.provider=x-ray
```

Workaround as of now is to run command like below, but it would be great if you can update README to specify this.  I've spent considerable amount of time troubleshooting this. 

```
helm upgrade -i appmesh-inject eks/appmesh-inject \
--namespace appmesh-system \
--set tracing.enabled=true \
--set tracing.provider=x-ray \
--set mesh.name=<your_mesh_name>
```

**Comment by achevuru** [comment]
@petrokashlikov "appmesh-inject" repo is deprecated and we recommend you move to GA version of the controller @https://github.com/aws/aws-app-mesh-controller-for-k8s/releases. If you continue to run in to this issue with the GA version, feel free to reopen the issue.
