### ISSUE TITLE
[aws-vpc-cni] Upgrade from 1.0.2 to 1.0.3 failed

### ISSUE THREAD

**Issue by lyz-code** [aws/eks-charts#99]
While upgrading from the version 1.0.2 to version 1.0.3, the `aws-node` pods of the daemonset enter in `CrashLoopBackoff`

```
  Normal   Pulling    2m15s (x2 over 3m42s)  kubelet, ec2.internal  Pulling image "602401143452.dkr.ecr.us-west-1.amazonaws.com/amazon-k8s-cni:v1.5.5"
  Normal   Pulled     2m15s (x2 over 3m41s)  kubelet, ec2.internal  Successfully pulled image "602401143452.dkr.ecr.us-west-1.amazonaws.com/amazon-k8s-cni:v1.5.5"
  Normal   Created    2m15s (x2 over 3m41s)  kubelet, ec2.internal  Created container aws-node
  Normal   Started    2m15s (x2 over 3m41s)  kubelet, ec2.internal  Started container aws-node
  Warning  Unhealthy  76s (x6 over 3m6s)     kubelet, ec2.internal  Liveness probe failed: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/app/grpc-health-probe\": stat /app/grpc-health-probe: no such file or directory": unknown
  Normal   Killing    76s (x2 over 2m46s)    kubelet, ec2.internal  Container aws-node failed liveness probe, will be restarted
```

It don't know if its related, but it seems that in the Daemonset the image tag wasn't changed to `1.6.0`.

```yaml
        containers:
          - name: aws-node
            image: "602401143452.dkr.ecr.us-west-1.amazonaws.com/amazon-k8s-cni:v1.5.5"
```

Even when `helm ls` shows that version `1.6.0` of the application is installed:

```
NAME       	REVISION	UPDATED                 	STATUS         	CHART            	APP VERSION	NAMESPACE  
aws-vpc-cni	1       	Wed Mar 25 11:38:33 2020	PENDING_INSTALL	aws-vpc-cni-1.0.3	v1.6.0     	kube-system
```

**Comment by jaypipes** [comment]
That is odd, indeed, considering the image tag was set to `v1.6.0` for the chart's 1.0.3 release:

https://github.com/aws/eks-charts/blob/2ddfdaed9848dab80a67de33ee02d070a566a2f3/stable/aws-vpc-cni/values.yaml#L11

**Comment by jaypipes** [comment]
@lyz-code would you mind pasting the exact sequence of commands you executed when performing your upgrade? Thanks much!

**Comment by lyz-code** [comment]
Ouch, it seems I've got the tag in my helm chart `values.yaml` too. So if the chart gets updated, but my `values.yaml` file does not, the deployment fails.

Commenting out the `tag:` part of the `values.yaml` file solved the issue. 

I usually populate the first version of that file with `helm inspect values {{ chart_name }} > values.yaml`. Maybe it's a bad practice, but if other people do that too, they'll probably have the same problem as I do. If that's the case, It might be interesting to comment out by default that key.

**Comment by max-rocket-internet** [comment]
> Maybe it's a bad practice

I would say yes 🙂
