### ISSUE TITLE
Can't install TargetGroupBinding CRDs with k8s 1.28

### ISSUE THREAD

**Issue by mhenson1** [aws/eks-charts#994]
**Describe the bug**
I tried installing the TargetGroupBinding CRDs today, per the aws-load-balancer-controller instructions seen [here](https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller)

Install the TargetGroupBinding CRDs
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

but I get this error
error: failed to run '/usr/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/aws-load-balancer-controller master': fatal: repository 'https://github.com/aws/eks-charts/stable/aws-load-balancer-controller/' not found

**Steps to reproduce**
Run this command
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"

**Expected outcome**
The CRDs to be created in my cluster.

**Environment**

* Chart name: aws-load-balancer-controller
* Kubernetes version: 1.28
* Using EKS (yes/no), if so version? Yes, 1.27

**Comment by mhenson1** [comment]
I edited the title because I did some more testing. I put k8s 1.26 on my machine and was able to run the command successfully, but after updating to 1.28 I started getting the "failed to run" error.

**Comment by mhenson1** [comment]
As a workaround, I've adjusted our automation to do this

wget https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
kubectl apply -f crds.yaml

**Comment by bryantbiggs** [comment]
the URL is incorrect, there should only be one `/` after `crds`

` kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"`
